key: docker.ps
name: Docker PS
short_desc: List running Docker containers with status, ports, and resource usage information.
platform:
  - docker
  - linux
tags:
  - docker
  - containers
  - monitoring
meta:
  cmd: "docker ps -a --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}'"
  requires_docker: true