# OpsConductor V3 - Phase 5: Simplified Traefik Deployment
# Deploy Traefik alongside existing services for testing

services:
  # Traefik Reverse Proxy
  traefik:
    build: ./traefik
    container_name: opsconductor-traefik
    ports:
      - "8082:80"    # HTTP (alternative port to avoid conflict with Nginx)
      - "8443:443"   # HTTPS (alternative port)
      - "8081:8081"  # Traefik dashboard
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_DEBUG=true
      - TRAEFIK_METRICS_PROMETHEUS=true
    volumes:
      # Docker socket for service discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Configuration files
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # SSL certificates storage
      - traefik_letsencrypt:/letsencrypt
      # Logs
      - traefik_logs:/var/log/traefik
    networks:
      - opsconductor-net
    labels:
      # Traefik configuration via labels
      - "traefik.enable=true"
      
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=traefik"
      
      # Dashboard authentication
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$2y$$10$$2b2cu/0P6eBi4Ej1iBXXhOaohvZabfQANjU7fCzCqz9OeUPuVJ3Pu"
      
      # Metrics endpoint
      - "traefik.http.routers.metrics.rule=Host(`localhost`) && Path(`/metrics`)"
      - "traefik.http.routers.metrics.service=prometheus@internal"
      - "traefik.http.routers.metrics.entrypoints=traefik"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  opsconductor-net:
    name: opsconductor-ng_opsconductor-net
    external: true

volumes:
  traefik_letsencrypt:
    driver: local
  traefik_logs:
    driver: local