version: '3.8'

services:
  # Enhanced Redis with Streams configuration
  redis-streams:
    image: redis:7.4-alpine
    container_name: opsconductor-redis-streams
    ports:
      - "6380:6379"  # Different port to run alongside existing Redis
    volumes:
      - redis_streams_data:/data
      - ./redis-streams/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "opsconductor-streams-2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - opsconductor-net
    environment:
      - REDIS_REPLICATION_MODE=master
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      memlock: -1
      nofile: 65535

volumes:
  redis_streams_data:
    driver: local

networks:
  opsconductor-net:
    external: true