services:
  automation-service:
    healthcheck:
      test: ["CMD","python","scripts/selector_healthz.py","--timeout","1.5","--k","1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      PYTHONPATH: /app
      SELECTOR_K_DEFAULT: "20"
      ALWAYS_INCLUDE_TOOLS: asset-query,service-status,network-ping
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
