version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: opsconductor-postgres
    environment:
      POSTGRES_DB: opsconductor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    ports:
      - "5432:5432"
    networks:
      - opsconductor-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: opsconductor-auth
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
      JWT_SECRET_KEY: your-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./auth-service/main.py:/app/main.py
      - ./auth-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service:
    build: ./user-service
    container_name: opsconductor-users
    ports:
      - "3002:3002"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./user-service/main.py:/app/main.py
      - ./user-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  credentials-service:
    build: ./credentials-service
    container_name: opsconductor-credentials
    ports:
      - "3004:3004"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
      ENCRYPTION_KEY: your-encryption-key-here
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./credentials-service/main.py:/app/main.py
      - ./credentials-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  targets-service:
    build: ./targets-service
    container_name: opsconductor-targets
    ports:
      - "3005:3005"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./targets-service/main.py:/app/main.py
      - ./targets-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  jobs-service:
    build: ./jobs-service
    container_name: opsconductor-jobs
    ports:
      - "3006:3006"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./jobs-service/main.py:/app/main.py
      - ./jobs-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  executor-service:
    build: ./executor-service
    container_name: opsconductor-executor
    ports:
      - "3007:3007"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./executor-service/main.py:/app/main.py
      - ./executor-service/ssh_executor.py:/app/ssh_executor.py
      - ./executor-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler-service:
    build: ./scheduler-service
    container_name: opsconductor-scheduler
    ports:
      - "3008:3008"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./scheduler-service/main.py:/app/main.py
      - ./scheduler-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    build: ./notification-service
    container_name: opsconductor-notification
    ports:
      - "3009:3009"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: your-email@gmail.com
      SMTP_PASSWORD: your-app-password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./notification-service/main.py:/app/main.py
      - ./notification-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  discovery-service:
    build: ./discovery-service
    container_name: opsconductor-discovery
    ports:
      - "3010:3010"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: opsconductor
      JWT_SECRET_KEY: your-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opsconductor-net
    volumes:
      - ./discovery-service/main.py:/app/main.py
      - ./discovery-service/shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: opsconductor-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    ports:
      - "3000:3000"
    networks:
      - opsconductor-net
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    container_name: opsconductor-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - auth-service
      - user-service
      - credentials-service
      - targets-service
      - jobs-service
      - executor-service
      - scheduler-service
      - notification-service
    networks:
      - opsconductor-net
    volumes:
      - nginx_ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  opsconductor-net:
    driver: bridge

volumes:
  postgres_data:
  nginx_ssl: