services:
  kong:
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    volumes:
      - ./config/kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "0.0.0.0:8000:8000"  # HTTP proxy
      - "0.0.0.0:8443:8443"  # HTTPS proxy (optional)
