# Docker Compose GPU Override
# Use this file to ensure proper GPU access for AI services in VMs with vfio-pci passthrough
# Usage: docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up

services:
  # AI Brain Service with GPU support (vfio-pci VM compatibility)
  ai-brain:
    runtime: nvidia
    privileged: true  # Required for vfio-pci GPU passthrough in VMs
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all  # Use 'all' for VM compatibility
      - NVIDIA_DISABLE_REQUIRE=1  # Disable some checks that fail in VMs
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-caps:/dev/nvidia-caps
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.580.82.09:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libcuda.so.580.82.09:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Ollama with GPU support (vfio-pci VM compatibility)
  ollama:
    runtime: nvidia
    privileged: true  # Required for vfio-pci GPU passthrough in VMs
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all  # Use 'all' for VM compatibility
      - NVIDIA_DISABLE_REQUIRE=1  # Disable some checks that fail in VMs
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-caps:/dev/nvidia-caps
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.580.82.09:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libcuda.so.580.82.09:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]