services:
  # Sidecar publisher for host:8020 -> automation-service:3003
  selector-pub:
    image: alpine/socat
    command: ["-dd", "TCP-LISTEN:3003,fork,reuseaddr", "TCP:127.0.0.1:3003"]
    network_mode: "service:automation-service"
    depends_on:
      automation-service:
        condition: service_started
    ports:
      - "0.0.0.0:8020:3003"
