version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
        - DOCKER_BUILDKIT=1
      no_cache: true
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reloading (optional)
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro