networks:
  opsconductor-dev:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  ollama_models:
  prefect_data:

services:
  # Core Infrastructure
  postgres:
    image: postgres:17-alpine
    container_name: opsconductor-postgres-dev
    environment:
      POSTGRES_DB: opsconductor
      POSTGRES_USER: opsconductor
      POSTGRES_PASSWORD: opsconductor_secure_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    networks:
      - opsconductor-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opsconductor"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: opsconductor-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - opsconductor-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AI Infrastructure
  ollama:
    image: ollama/ollama:0.11.11
    container_name: opsconductor-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - opsconductor-dev
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Orchestration Engine
  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: opsconductor-prefect-dev
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_API_PORT: 4200
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_SERVER_DATABASE_CONNECTION_URL: postgresql+asyncpg://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Kong API Gateway
  kong:
    image: kong:3.4
    container_name: opsconductor-kong-dev
    ports:
      - "3000:8000"     # Main API Gateway port
      - "8888:8001"     # Kong Admin API (moved to avoid conflict)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    networks:
      - opsconductor-dev
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Keycloak Identity Provider
  keycloak:
    image: keycloak/keycloak:22.0.1
    container_name: opsconductor-keycloak-dev
    ports:
      - "8090:8080"   # Keycloak admin and auth port
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/opsconductor"
      KC_DB_USERNAME: opsconductor
      KC_DB_PASSWORD: opsconductor_secure_2024
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: OpsConductor2024!
    command: 
      - start
      - --import-realm
    volumes:
      - ./keycloak/opsconductor-realm.json:/opt/keycloak/data/import/opsconductor-realm.json:ro
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /auth/realms/master HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;grep 'HTTP/1.1 200 OK' <&3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # NEW 4-Stage AI Pipeline - NEWIDEA.MD Architecture
  ai-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opsconductor-ai-pipeline-dev
    environment:
      OLLAMA_BASE_URL: http://opsconductor-ollama-dev:11434
      OLLAMA_MODEL: qwen2.5:14b-instruct-q4_k_m
      PREFECT_API_URL: http://prefect-server:4200/api
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
      AUTOMATION_SERVICE_URL: http://automation-service:8010
      ASSET_SERVICE_URL: http://asset-service:8002
      NETWORK_SERVICE_URL: http://network-service:8003
      COMMUNICATION_SERVICE_URL: http://communication-service:8004
    ports:
      - "3005:8000"
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes for 4-stage pipeline
      - ./main.py:/app/main.py
      - ./pipeline:/app/pipeline
      - ./llm:/app/llm
      - ./capabilities:/app/capabilities
      - ./execution:/app/execution
      - ./api:/app/api
      - ./shared:/app/shared
    networks:
      - opsconductor-dev
    depends_on:
      prefect-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Specialized Services
  automation-service:
    build:
      context: ./automation-service
      dockerfile: Dockerfile.clean
    container_name: opsconductor-automation-dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
      REDIS_URL: redis://redis:6379
    ports:
      - "8010:3003"
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes
      - ./automation-service/main_clean.py:/app/main_clean.py
      - ./automation-service/libraries:/app/libraries
      - ./shared:/app/shared
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  asset-service:
    build:
      context: ./asset-service
      dockerfile: Dockerfile
    container_name: opsconductor-assets-dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
      REDIS_URL: redis://redis:6379
    ports:
      - "8002:3002"
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes
      - ./asset-service/main.py:/app/main.py
      - ./asset-service/data:/app/data
      - ./shared:/app/shared
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  network-service:
    build:
      context: ./network-analyzer-service
      dockerfile: Dockerfile
    container_name: opsconductor-network-dev
    environment:
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
      REDIS_URL: redis://redis:6379
    ports:
      - "8003:8003"
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes
      - ./network-analyzer-service/main.py:/app/main.py
      - ./network-analyzer-service/agents:/app/agents
      - ./network-analyzer-service/analyzers:/app/analyzers
      - ./network-analyzer-service/models:/app/models
      - ./network-analyzer-service/utils:/app/utils
      - ./shared:/app/shared
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  communication-service:
    build:
      context: ./communication-service
      dockerfile: Dockerfile
    container_name: opsconductor-communication-dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
      REDIS_URL: redis://redis:6379
    ports:
      - "8004:8004"
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes
      - ./communication-service/main.py:/app/main.py
      - ./shared:/app/shared
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    container_name: opsconductor-identity-dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://opsconductor:opsconductor_secure_2024@postgres:5432/opsconductor
      REDIS_URL: redis://redis:6379
    ports:
      - "8005:8005"
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes
      - ./identity-service/main.py:/app/main.py
      - ./identity-service/keycloak_adapter.py:/app/keycloak_adapter.py
      - ./shared:/app/shared
    networks:
      - opsconductor-dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (Development with live reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: opsconductor-frontend-dev
    ports:
      - "3100:3000"  # Expose on 3100 to avoid Kong conflict
    volumes:
      # DEVELOPMENT VOLUME MOUNTS - Live file changes for React development
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/.env:/app/.env
    networks:
      - opsconductor-dev
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload in Docker
      - REACT_APP_API_URL=http://192.168.10.50:3000  # Use Kong gateway
    depends_on:
      - ai-pipeline