# Axis VAPIX PTZ Control - Control Axis camera PTZ (Pan/Tilt/Zoom) via VAPIX API
tool_name: Axis-VAPIX-PTZ
version: '1.0'
description: Control Axis camera PTZ (Pan/Tilt/Zoom) functions via VAPIX HTTP API
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/com/ptz.cgi
  auth_type: digest
  method: GET
capabilities:
  goto_preset:
    description: Move camera to a saved preset position by name
    patterns:
      move_to_preset_by_name:
        description: Move Axis camera to preset position using preset name
        typical_use_cases:
        - move axis camera to preset
        - go to preset position
        - move camera to wall preset
        - move camera to home preset
        - axis camera goto preset
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: preset_name
          type: string
          description: Name of the preset position to move to
          validation: .+
        api_parameters:
          gotoserverpresetname: "{preset_name}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?gotoserverpresetname={preset_name}"
      move_to_preset_by_number:
        description: Move Axis camera to preset position using preset number
        typical_use_cases:
        - move axis camera to preset number
        - go to preset 1
        - axis camera goto preset number
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: preset_number
          type: integer
          description: Number of the preset position to move to (1-100)
          validation: ^[1-9][0-9]?$|^100$
        api_parameters:
          gotoserverpresetno: "{preset_number}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?gotoserverpresetno={preset_number}"
  absolute_move:
    description: Move camera to absolute pan/tilt position
    patterns:
      absolute_position:
        description: Move camera to specific pan/tilt coordinates
        typical_use_cases:
        - move camera to absolute position
        - set camera pan tilt
        - axis camera absolute move
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.6
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: pan
          type: float
          description: Pan position in degrees (-180 to 180)
          validation: ^-?([0-9]|[1-9][0-9]|1[0-7][0-9]|180)(\.[0-9]+)?$
        - name: tilt
          type: float
          description: Tilt position in degrees (-180 to 180)
          validation: ^-?([0-9]|[1-9][0-9]|1[0-7][0-9]|180)(\.[0-9]+)?$
        - name: zoom
          type: integer
          description: Zoom level (1-9999, optional)
          validation: ^[1-9][0-9]{0,3}$
          required: false
        api_parameters:
          pan: "{pan}"
          tilt: "{tilt}"
          zoom: "{zoom}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?pan={pan}&tilt={tilt}&zoom={zoom}"
  relative_move:
    description: Move camera relative to current position
    patterns:
      relative_position:
        description: Move camera by relative pan/tilt offset
        typical_use_cases:
        - move camera left
        - move camera right
        - pan camera
        - tilt camera up
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.6
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: rpan
          type: float
          description: Relative pan movement in degrees
          validation: ^-?[0-9]+(\.[0-9]+)?$
        - name: rtilt
          type: float
          description: Relative tilt movement in degrees
          validation: ^-?[0-9]+(\.[0-9]+)?$
        - name: rzoom
          type: integer
          description: Relative zoom movement (optional)
          validation: ^-?[0-9]+$
          required: false
        api_parameters:
          rpan: "{rpan}"
          rtilt: "{rtilt}"
          rzoom: "{rzoom}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?rpan={rpan}&rtilt={rtilt}&rzoom={rzoom}"
  zoom_control:
    description: Control camera zoom (in/out)
    patterns:
      zoom_in:
        description: Zoom in the camera by a relative amount
        typical_use_cases:
        - zoom in
        - zoom in 2x
        - zoom in camera
        - increase zoom
        - zoom camera in
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: zoom_amount
          type: integer
          description: Relative zoom amount (positive = zoom in, typical range 500-5000, default 1000)
          validation: ^[1-9][0-9]{2,4}$
          default: 1000
        api_parameters:
          rzoom: "{zoom_amount}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?rzoom={zoom_amount}"
      zoom_out:
        description: Zoom out the camera by a relative amount
        typical_use_cases:
        - zoom out
        - zoom out 2x
        - zoom out camera
        - decrease zoom
        - zoom camera out
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: zoom_amount
          type: integer
          description: Relative zoom amount (negative = zoom out, typical range -5000 to -500, default -1000)
          validation: ^-[1-9][0-9]{2,4}$
          default: -1000
        api_parameters:
          rzoom: "{zoom_amount}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?rzoom={zoom_amount}"
      absolute_zoom:
        description: Set camera to absolute zoom level
        typical_use_cases:
        - set zoom to level
        - zoom to specific level
        - absolute zoom
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: zoom_level
          type: integer
          description: Absolute zoom level (1-9999, where 1 is widest and 9999 is most zoomed in)
          validation: ^[1-9][0-9]{0,3}$
        api_parameters:
          zoom: "{zoom_level}"
        example_request: "GET http://{host}/axis-cgi/com/ptz.cgi?zoom={zoom_level}"
metadata:
  author: OpsConductor Team
  created: '2025-10-08'
  updated: '2025-10-08'
  tags:
  - axis
  - vapix
  - camera
  - ptz
  - network
  - surveillance
  documentation_url: https://www.axis.com/vapix-library/subjects/t10037719/section/t10004596/display
  api_reference: https://www.axis.com/vapix-library/
  notes: |
    Axis VAPIX PTZ Control API
    
    Authentication: HTTP Digest Authentication (recommended) or Basic Auth
    
    Common Parameters:
    - gotoserverpresetname=<name> : Move to preset by name
    - gotoserverpresetno=<number> : Move to preset by number (1-100)
    - pan=<degrees> : Absolute pan position (-180 to 180)
    - tilt=<degrees> : Absolute tilt position (-180 to 180)
    - zoom=<value> : Absolute zoom level (1-9999)
    - rpan=<degrees> : Relative pan movement
    - rtilt=<degrees> : Relative tilt movement
    - rzoom=<value> : Relative zoom movement
    
    Response: HTTP 204 No Content on success
    
    Example URLs:
    - Move to preset: http://camera/axis-cgi/com/ptz.cgi?gotoserverpresetname=wall
    - Absolute move: http://camera/axis-cgi/com/ptz.cgi?pan=90&tilt=0&zoom=1
    - Relative move: http://camera/axis-cgi/com/ptz.cgi?rpan=10&rtilt=-5
    - Zoom in: http://camera/axis-cgi/com/ptz.cgi?rzoom=1000
    - Zoom out: http://camera/axis-cgi/com/ptz.cgi?rzoom=-1000
    - Absolute zoom: http://camera/axis-cgi/com/ptz.cgi?zoom=5000