# ssh-analyzer - Analyze SSH protocol traffic
tool_name: ssh-analyzer
version: '1.0'
description: Analyze SSH protocol traffic
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  protocol_analysis:
    description: protocol_analysis capability
    patterns:
      analyze_ssh:
        description: analyze_ssh pattern
        typical_use_cases:
        - analyze ssh
        - ssh connections
        - ssh traffic
        time_estimate_ms: 1000 + 0.5 * packet_count
        cost_estimate: ceil(packet_count / 1000)
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - network
  - network
  - ssh-analyzer
  documentation_url: https://docs.opsconductor.io/tools/ssh-analyzer

# === EXAMPLES ===
examples:
  - name: "Analyze Ssh"
    description: "analyze_ssh pattern"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 1000
    expected_cost: 1
