# az-vm - Azure Virtual Machine management
tool_name: az-vm
execution_location: automation-service
version: '1.0'
description: Azure Virtual Machine management
platform: cloud
category: cloud
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: az-vm primary capability
    patterns:
      execute:
        description: Execute az-vm command
        typical_use_cases:
        - use az-vm
        - az-vm command
        - azure virtual machine management
        time_estimate_ms: '2000'
        cost_estimate: '5'
        complexity_score: 0.5
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - cloud
  - cloud
  - az-vm
  documentation_url: https://docs.opsconductor.io/tools/az-vm

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute az-vm command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 2000
    expected_cost: 5
