# Axis VAPIX Imaging - Control camera image quality settings via VAPIX API
tool_name: Axis-VAPIX-Imaging
execution_location: network-service
version: '1.0'
description: |
  Control Axis camera image quality settings via VAPIX API.
  Supports brightness, contrast, saturation, sharpness, and other image parameters.
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/param.cgi
  auth_type: digest
  method: GET
capabilities:
  set_image_settings:
    description: Configure camera image quality parameters
    patterns:
      adjust_brightness:
        description: Adjust camera brightness level
        typical_use_cases:
        - increase brightness
        - decrease brightness
        - set brightness
        - make image brighter
        - make image darker
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: brightness
          type: integer
          description: |
            Brightness level for the camera image.
            
            VALUE MEANINGS:
            - Range: 0-100
            - 0: Darkest (minimum brightness)
            - 50: Default/neutral brightness
            - 100: Brightest (maximum brightness)
            
            WHEN TO USE:
            - Increase for dark scenes or backlighting
            - Decrease for overly bright scenes
            - Adjust when image is too dark or too bright
            
            NATURAL LANGUAGE MAPPING:
            - "make brighter" → increase by 10-20 (e.g., 50 → 70)
            - "make darker" → decrease by 10-20 (e.g., 50 → 30)
            - "very bright" → 80-100
            - "very dark" → 0-20
            - "normal brightness" → 50
            
            EXAMPLES:
            - 30 - Darker than default
            - 50 - Default brightness
            - 70 - Brighter than default
          validation: ^([0-9]|[1-9][0-9]|100)$
        api_parameters:
          action: "update"
          ImageSource.I0.Sensor.Brightness: "{brightness}"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Brightness={brightness}"
      adjust_contrast:
        description: Adjust camera contrast level
        typical_use_cases:
        - increase contrast
        - decrease contrast
        - set contrast
        - adjust image contrast
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: contrast
          type: integer
          description: |
            Contrast level for the camera image.
            
            VALUE MEANINGS:
            - Range: 0-100
            - 0: Minimum contrast (flat, washed out)
            - 50: Default/neutral contrast
            - 100: Maximum contrast (strong difference between light and dark)
            
            WHEN TO USE:
            - Increase for foggy/hazy conditions
            - Decrease for harsh lighting with strong shadows
            - Adjust when image lacks definition or is too harsh
            
            NATURAL LANGUAGE MAPPING:
            - "increase contrast" → increase by 10-20 (e.g., 50 → 70)
            - "decrease contrast" → decrease by 10-20 (e.g., 50 → 30)
            - "high contrast" → 70-100
            - "low contrast" → 0-30
            - "normal contrast" → 50
            
            EXAMPLES:
            - 30 - Lower contrast (softer image)
            - 50 - Default contrast
            - 70 - Higher contrast (more definition)
          validation: ^([0-9]|[1-9][0-9]|100)$
        api_parameters:
          action: "update"
          ImageSource.I0.Sensor.Contrast: "{contrast}"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Contrast={contrast}"
      adjust_saturation:
        description: Adjust camera color saturation level
        typical_use_cases:
        - increase saturation
        - decrease saturation
        - set saturation
        - make colors more vivid
        - make colors less vivid
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: saturation
          type: integer
          description: |
            Color saturation level for the camera image.
            
            VALUE MEANINGS:
            - Range: 0-100
            - 0: Grayscale (no color)
            - 50: Default/neutral saturation
            - 100: Maximum saturation (very vivid colors)
            
            WHEN TO USE:
            - Increase for more vivid, vibrant colors
            - Decrease for more muted, natural colors
            - Set to 0 for black and white image
            
            NATURAL LANGUAGE MAPPING:
            - "more colorful" → increase by 10-20 (e.g., 50 → 70)
            - "less colorful" → decrease by 10-20 (e.g., 50 → 30)
            - "vivid colors" → 70-100
            - "muted colors" → 20-40
            - "black and white" → 0
            - "normal colors" → 50
            
            EXAMPLES:
            - 0 - Black and white
            - 30 - Muted colors
            - 50 - Default saturation
            - 80 - Vivid colors
          validation: ^([0-9]|[1-9][0-9]|100)$
        api_parameters:
          action: "update"
          ImageSource.I0.Sensor.ColorLevel: "{saturation}"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.ColorLevel={saturation}"
      adjust_sharpness:
        description: Adjust camera image sharpness level
        typical_use_cases:
        - increase sharpness
        - decrease sharpness
        - set sharpness
        - make image sharper
        - make image softer
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: sharpness
          type: integer
          description: |
            Sharpness level for the camera image.
            
            VALUE MEANINGS:
            - Range: 0-100
            - 0: Minimum sharpness (soft, blurry)
            - 50: Default/neutral sharpness
            - 100: Maximum sharpness (very crisp edges)
            
            WHEN TO USE:
            - Increase for clearer details and edges
            - Decrease to reduce noise or soften image
            - Be careful: too much sharpness can amplify noise
            
            NATURAL LANGUAGE MAPPING:
            - "sharper image" → increase by 10-20 (e.g., 50 → 70)
            - "softer image" → decrease by 10-20 (e.g., 50 → 30)
            - "very sharp" → 70-100
            - "soft focus" → 0-30
            - "normal sharpness" → 50
            
            EXAMPLES:
            - 30 - Softer image
            - 50 - Default sharpness
            - 70 - Sharper image
          validation: ^([0-9]|[1-9][0-9]|100)$
        api_parameters:
          action: "update"
          ImageSource.I0.Sensor.Sharpness: "{sharpness}"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Sharpness={sharpness}"
  get_image_settings:
    description: Retrieve current image quality settings
    patterns:
      get_current_settings:
        description: Get current brightness, contrast, saturation, and sharpness values
        typical_use_cases:
        - get image settings
        - check current brightness
        - view image parameters
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 3
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        api_parameters:
          action: "list"
          group: "ImageSource.I0.Sensor"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=list&group=ImageSource.I0.Sensor"
metadata:
  author: OpsConductor Team
  created: '2025-01-15'
  updated: '2025-01-15'
  tags:
  - axis
  - vapix
  - camera
  - imaging
  - brightness
  - contrast
  - saturation
  - sharpness
  - image quality
  documentation_url: https://developer.axis.com/vapix/network-video/imaging-api/
  api_reference: https://developer.axis.com/vapix/
  notes: |
    Axis VAPIX Imaging API
    
    PARAMETER MANAGEMENT:
    - Uses param.cgi for getting and setting parameters
    - action=update : Set parameter values
    - action=list : Get parameter values
    
    COMMON IMAGE PARAMETERS:
    - ImageSource.I0.Sensor.Brightness : Brightness level (0-100)
    - ImageSource.I0.Sensor.Contrast : Contrast level (0-100)
    - ImageSource.I0.Sensor.ColorLevel : Saturation level (0-100)
    - ImageSource.I0.Sensor.Sharpness : Sharpness level (0-100)
    - ImageSource.I0.Sensor.WDR : Wide Dynamic Range (on/off)
    - ImageSource.I0.Sensor.ExposureValue : Exposure compensation
    
    MULTI-CAMERA PRODUCTS:
    - Replace I0 with I1, I2, etc. for additional cameras
    - Example: ImageSource.I1.Sensor.Brightness for camera 2
    
    RESPONSE FORMAT:
    - Success: HTTP 200 OK with parameter values
    - Format: parameter=value (one per line)
    
    EXAMPLES:
    
    1. Set brightness to 70:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Brightness=70
    
    2. Set contrast to 60:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Contrast=60
    
    3. Set saturation to 80:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.ColorLevel=80
    
    4. Set sharpness to 55:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Sharpness=55
    
    5. Get all image sensor settings:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=list&group=ImageSource.I0.Sensor
    
    6. Set multiple parameters at once:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update&ImageSource.I0.Sensor.Brightness=70&ImageSource.I0.Sensor.Contrast=60
    
    BEST PRACTICES:
    - Make incremental adjustments (10-20 points at a time)
    - Test settings in actual lighting conditions
    - Consider using scene profiles for different lighting scenarios
    - Avoid extreme values (0 or 100) unless specifically needed

# === EXAMPLES ===
examples:
  - name: "Adjust Brightness"
    description: "Adjust camera brightness level"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      brightness: 100
    expected_time_ms: 1000
    expected_cost: 1
  - name: "Adjust Contrast"
    description: "Adjust camera contrast level"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      contrast: 100
    expected_time_ms: 1000
    expected_cost: 1
  - name: "Adjust Saturation"
    description: "Adjust camera color saturation level"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      saturation: 100
    expected_time_ms: 1000
    expected_cost: 1
  - name: "Get Current Settings"
    description: "Get current brightness, contrast, saturation, and sharpness values"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
    expected_time_ms: 500
    expected_cost: 1
