-- Phase 11.1: Notification Steps Database Schema
-- Job notification steps for contextual notifications within workflows

-- Notification step execution tracking
CREATE TABLE IF NOT EXISTS notification_step_executions (
    id BIGSERIAL PRIMARY KEY,
    job_run_step_id BIGINT REFERENCES job_run_steps(id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL CHECK (notification_type IN ('email', 'slack', 'teams', 'webhook')),
    recipients JSONB NOT NULL,
    subject TEXT,
    content TEXT,
    delivery_status VARCHAR(50) DEFAULT 'pending' CHECK (delivery_status IN ('pending', 'sent', 'failed', 'retrying')),
    delivery_attempts INTEGER DEFAULT 0,
    delivered_at TIMESTAMPTZ,
    error_message TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for notification_step_executions
CREATE INDEX IF NOT EXISTS idx_notification_step_executions_job_run_step_id ON notification_step_executions(job_run_step_id);
CREATE INDEX IF NOT EXISTS idx_notification_step_executions_notification_type ON notification_step_executions(notification_type);
CREATE INDEX IF NOT EXISTS idx_notification_step_executions_delivery_status ON notification_step_executions(delivery_status);
CREATE INDEX IF NOT EXISTS idx_notification_step_executions_created_at ON notification_step_executions(created_at);

-- Extend notification_templates for job step notifications
-- Add step-specific template types
INSERT INTO notification_templates (channel, event_type, name, description, subject_template, body_template, is_default, is_active) VALUES
-- Email step notification templates
('email', 'step_notification', 'Job Step Notification', 'Template for job step notifications via email', 
 'OpsConductor: {{ job.name }} - Step Notification', 
 '<html><body><h2>Job Step Notification</h2><p>This is a notification from job step execution.</p><h3>Job Details:</h3><ul><li><strong>Job:</strong> {{ job.name }}</li><li><strong>Target:</strong> {{ target.name }} ({{ target.hostname }})</li><li><strong>Status:</strong> {{ job.status }}</li><li><strong>Duration:</strong> {{ job.execution_time_ms | duration }}</li><li><strong>Steps:</strong> {{ job.completed_steps }}/{{ job.total_steps }}</li></ul>{% if job.status == "failed" %}<h3>Error Details:</h3><pre style="background: #f8d7da; padding: 10px; border-radius: 3px;">{% for step_name, step in steps.items() %}{% if step.status == "failed" %}{{ step_name }}: {{ step.error_message }}{% endif %}{% endfor %}</pre>{% endif %}<p><small>Generated by OpsConductor at {{ system.timestamp }}</small></p></body></html>', 
 true, true),

-- Slack step notification templates
('slack', 'step_notification', 'Job Step Notification', 'Template for job step notifications via Slack',
 null,
 '{"text": "📋 Job Step Notification", "blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "*Job Step Notification*\\n{{ job.name }} on {{ target.hostname }}"}}, {"type": "section", "fields": [{"type": "mrkdwn", "text": "*Job:*\\n{{ job.name }}"}, {"type": "mrkdwn", "text": "*Target:*\\n{{ target.hostname }}"}, {"type": "mrkdwn", "text": "*Status:*\\n{{ job.status | upper }}"}, {"type": "mrkdwn", "text": "*Duration:*\\n{{ job.execution_time_ms }}ms"}]}]}',
 true, true),

-- Teams step notification templates
('teams', 'step_notification', 'Job Step Notification', 'Template for job step notifications via Teams',
 'Job Step Notification',
 '{"@type": "MessageCard", "@context": "http://schema.org/extensions", "themeColor": "{{ job.status | status_color }}", "summary": "Job {{ job.name }} step notification", "sections": [{"activityTitle": "Job Step Notification", "activitySubtitle": "{{ job.name }}", "facts": [{"name": "Job", "value": "{{ job.name }}"}, {"name": "Target", "value": "{{ target.hostname }}"}, {"name": "Status", "value": "{{ job.status | upper }}"}, {"name": "Duration", "value": "{{ job.execution_time_ms }}ms"}]}]}',
 true, true),

-- Webhook step notification templates
('webhook', 'step_notification', 'Job Step Notification', 'Template for job step notifications via webhook',
 null,
 '{"event": "step_notification", "job": {"id": {{ job.id }}, "name": "{{ job.name }}", "status": "{{ job.status }}", "execution_time_ms": {{ job.execution_time_ms }}, "completed_steps": {{ job.completed_steps }}, "total_steps": {{ job.total_steps }}}, "target": {"id": {{ target.id }}, "name": "{{ target.name }}", "hostname": "{{ target.hostname }}"}, "user": {"id": {{ user.id }}, "username": "{{ user.username }}", "email": "{{ user.email }}"}, "timestamp": "{{ system.timestamp }}"}',
 true, true)
ON CONFLICT (channel, event_type, name) DO NOTHING;

-- Add comments for documentation
COMMENT ON TABLE notification_step_executions IS 'Tracks execution of notification steps within job workflows';
COMMENT ON COLUMN notification_step_executions.job_run_step_id IS 'Reference to the job run step that triggered this notification';
COMMENT ON COLUMN notification_step_executions.notification_type IS 'Type of notification: email, slack, teams, webhook';
COMMENT ON COLUMN notification_step_executions.recipients IS 'JSON array of notification recipients';
COMMENT ON COLUMN notification_step_executions.delivery_status IS 'Current delivery status of the notification';
COMMENT ON COLUMN notification_step_executions.metadata IS 'Additional metadata about the notification execution';