# chown - Change file ownership
tool_name: "chown"
version: "1.0"
description: "Change file owner and group ownership for files and directories"
platform: "linux"
category: "security"

defaults:
  accuracy_level: "real-time"
  freshness: "live"
  data_source: "filesystem"

capabilities:
  ownership_management:
    description: "Modify file and directory ownership (user and group)"
    
    patterns:
      change_owner:
        description: "Change file owner (user)"
        
        typical_use_cases:
          - "change file owner"
          - "transfer file ownership"
          - "fix ownership issues"
          - "assign file to user"
          - "chown user"
        
        time_estimate_ms: "150 + 50 * num_files"
        cost_estimate: "2"
        complexity_score: 0.3
        
        scope: "single_item"
        completeness: "complete"
        
        limitations:
          - "Requires root/sudo privileges"
          - "Cannot change ownership of files you don't own (unless root)"
          - "Symbolic links not followed by default"
          - "Does not modify ACLs"
          - "User must exist on system"
        
        policy:
          max_cost: 5
          requires_approval: true
          production_safe: false
          max_execution_time: 30
        
        preference_match:
          speed: 0.9
          accuracy: 1.0
          cost: 0.85
          complexity: 0.85
          completeness: 1.0
        
        required_inputs:
          - name: "path"
            type: "string"
            description: "File or directory path to change ownership. Can be absolute or relative path"
            validation: ".*"
            examples:
              - "/var/www/html"
              - "/home/user/file.txt"
              - "/etc/nginx/nginx.conf"
          - name: "owner"
            type: "string"
            description: "New owner username or UID. Examples: 'www-data', 'root', '1000'"
            validation: "^[a-zA-Z_][a-zA-Z0-9_-]*$|^\\d+$"
            examples:
              - "www-data"
              - "root"
              - "nginx"
              - "1000"
          - name: "host"
            type: "string"
            description: "Target host where chown will be executed"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
            examples:
              - "web-server-01"
              - "192.168.1.100"
        
        optional_inputs:
          - name: "recursive"
            type: "boolean"
            description: "Apply ownership change recursively to directories and contents (chown -R)"
            default: "false"
          - name: "verbose"
            type: "boolean"
            description: "Show detailed output of changes made"
            default: "false"
          - name: "dereference"
            type: "boolean"
            description: "Follow symbolic links and change target (default: don't follow)"
            default: "false"
        
        expected_outputs:
          - name: "success"
            type: "boolean"
            description: "Whether operation completed successfully"
          - name: "files_modified"
            type: "integer"
            description: "Number of files/directories modified"
          - name: "changes"
            type: "array"
            description: "List of files modified with old and new ownership"
      
      change_owner_and_group:
        description: "Change both file owner and group simultaneously"
        
        typical_use_cases:
          - "change owner and group"
          - "set file ownership"
          - "chown user:group"
          - "transfer complete ownership"
          - "fix ownership and group"
        
        time_estimate_ms: "150 + 50 * num_files"
        cost_estimate: "2"
        complexity_score: 0.3
        
        scope: "single_item"
        completeness: "complete"
        
        limitations:
          - "Requires root/sudo privileges"
          - "Both user and group must exist"
          - "Cannot change if not owner (unless root)"
        
        policy:
          max_cost: 5
          requires_approval: true
          production_safe: false
          max_execution_time: 30
        
        preference_match:
          speed: 0.9
          accuracy: 1.0
          cost: 0.85
          complexity: 0.85
          completeness: 1.0
        
        required_inputs:
          - name: "path"
            type: "string"
            description: "File or directory path"
            validation: ".*"
            examples:
              - "/var/www/html"
              - "/opt/application"
          - name: "owner"
            type: "string"
            description: "New owner username or UID"
            validation: "^[a-zA-Z_][a-zA-Z0-9_-]*$|^\\d+$"
            examples:
              - "www-data"
              - "nginx"
              - "1000"
          - name: "group"
            type: "string"
            description: "New group name or GID. Examples: 'www-data', 'docker', '1000'"
            validation: "^[a-zA-Z_][a-zA-Z0-9_-]*$|^\\d+$"
            examples:
              - "www-data"
              - "docker"
              - "wheel"
              - "1000"
          - name: "host"
            type: "string"
            description: "Target host for operation"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
        
        optional_inputs:
          - name: "recursive"
            type: "boolean"
            description: "Apply recursively"
            default: "false"
          - name: "verbose"
            type: "boolean"
            description: "Show detailed output"
            default: "false"
        
        expected_outputs:
          - name: "success"
            type: "boolean"
            description: "Operation success status"
          - name: "files_modified"
            type: "integer"
            description: "Number of files changed"
      
      change_group_only:
        description: "Change only the group ownership (equivalent to chgrp)"
        
        typical_use_cases:
          - "change file group"
          - "set group ownership"
          - "share files with group"
          - "fix group permissions"
        
        time_estimate_ms: "150 + 50 * num_files"
        cost_estimate: "2"
        complexity_score: 0.3
        
        scope: "single_item"
        completeness: "complete"
        
        limitations:
          - "Requires ownership or root privileges"
          - "Group must exist on system"
          - "User must be member of target group (unless root)"
        
        policy:
          max_cost: 5
          requires_approval: true
          production_safe: false
          max_execution_time: 30
        
        preference_match:
          speed: 0.9
          accuracy: 1.0
          cost: 0.85
          complexity: 0.85
          completeness: 1.0
        
        required_inputs:
          - name: "path"
            type: "string"
            description: "File or directory path"
            validation: ".*"
            examples:
              - "/var/shared/data"
              - "/home/project"
          - name: "group"
            type: "string"
            description: "New group name or GID"
            validation: "^[a-zA-Z_][a-zA-Z0-9_-]*$|^\\d+$"
            examples:
              - "developers"
              - "docker"
              - "www-data"
          - name: "host"
            type: "string"
            description: "Target host"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
        
        optional_inputs:
          - name: "recursive"
            type: "boolean"
            description: "Apply recursively"
            default: "false"
        
        expected_outputs:
          - name: "success"
            type: "boolean"
            description: "Whether group was changed"
          - name: "files_modified"
            type: "integer"
            description: "Number of files affected"
      
      bulk_ownership_fix:
        description: "Fix ownership for multiple files in directory tree"
        
        typical_use_cases:
          - "fix web directory ownership"
          - "restore proper ownership"
          - "standardize ownership"
          - "batch ownership updates"
          - "deployment ownership fix"
        
        time_estimate_ms: "500 + 100 * num_files"
        cost_estimate: "3"
        complexity_score: 0.4
        
        scope: "batch"
        completeness: "complete"
        
        limitations:
          - "Can affect many files"
          - "Requires root privileges"
          - "May take time for large directories"
          - "Cannot undo easily"
        
        policy:
          max_cost: 8
          requires_approval: true
          production_safe: false
          max_execution_time: 120
        
        preference_match:
          speed: 0.75
          accuracy: 1.0
          cost: 0.75
          complexity: 0.7
          completeness: 1.0
        
        required_inputs:
          - name: "directory"
            type: "string"
            description: "Base directory to fix ownership"
            validation: "^/.*"
            examples:
              - "/var/www/html"
              - "/opt/application"
          - name: "owner"
            type: "string"
            description: "Owner to set for all files"
            validation: "^[a-zA-Z_][a-zA-Z0-9_-]*$|^\\d+$"
            examples:
              - "www-data"
              - "nginx"
          - name: "group"
            type: "string"
            description: "Group to set for all files"
            validation: "^[a-zA-Z_][a-zA-Z0-9_-]*$|^\\d+$"
            examples:
              - "www-data"
              - "nginx"
          - name: "host"
            type: "string"
            description: "Target host"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
        
        optional_inputs:
          - name: "file_pattern"
            type: "string"
            description: "Only change files matching pattern"
            default: "*"
            examples:
              - "*.php"
              - "*.conf"
          - name: "exclude_pattern"
            type: "string"
            description: "Exclude files matching pattern"
            default: ""
            examples:
              - ".git"
              - "node_modules"
        
        expected_outputs:
          - name: "files_modified"
            type: "integer"
            description: "Number of files changed"
          - name: "dirs_modified"
            type: "integer"
            description: "Number of directories changed"
          - name: "summary"
            type: "object"
            description: "Summary of changes made"

dependencies:
  - name: "filesystem_access"
    type: "permission"
    required: true
  - name: "sudo_access"
    type: "permission"
    required: true
  - name: "coreutils"
    type: "package"
    required: true
    version: ">=8.0"

metadata:
  author: "OpsConductor Team"
  created: "2025-01-15"
  updated: "2025-01-15"
  tags:
    - "linux"
    - "security"
    - "ownership"
    - "filesystem"
    - "access-control"
  documentation_url: "https://man7.org/linux/man-pages/man1/chown.1.html"
  related_tools:
    - "chmod"
    - "chgrp"
    - "ls"
    - "stat"

examples:
  - name: "Change file owner"
    description: "Transfer file ownership to www-data user"
    inputs:
      path: "/var/www/html/index.html"
      owner: "www-data"
      host: "web-server-01"
    expected_time_ms: 150
    expected_cost: 2
  
  - name: "Set owner and group"
    description: "Set both owner and group for application directory"
    inputs:
      path: "/opt/application"
      owner: "appuser"
      group: "appgroup"
      host: "app-server-01"
      recursive: true
    expected_time_ms: 1000
    expected_cost: 2
  
  - name: "Fix web directory ownership"
    description: "Recursively set ownership for web root"
    inputs:
      directory: "/var/www/html"
      owner: "www-data"
      group: "www-data"
      host: "web-server-01"
    expected_time_ms: 2000
    expected_cost: 3
  
  - name: "Change group for shared directory"
    description: "Set group ownership for shared project directory"
    inputs:
      path: "/var/shared/project"
      group: "developers"
      host: "dev-server"
      recursive: true
    expected_time_ms: 800
    expected_cost: 2
  
  - name: "Fix deployment ownership"
    description: "Set proper ownership after deployment"
    inputs:
      directory: "/var/www/app"
      owner: "nginx"
      group: "nginx"
      host: "web-server-01"
      file_pattern: "*.php"
    expected_time_ms: 1500
    expected_cost: 3