# du - Display directory space usage
tool_name: du
execution_location: automation-service
version: '1.0'
description: Display directory space usage
platform: linux
category: system
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: du primary capability
    patterns:
      execute:
        description: Execute du command
        typical_use_cases:
        - use du
        - du command
        - display directory space usage
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - linux
  - system
  - du
  documentation_url: https://docs.opsconductor.io/tools/du

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute du command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 500
    expected_cost: 1
