# fail2ban-client - Intrusion prevention framework
tool_name: fail2ban-client
execution_location: automation-service
version: '1.0'
description: Intrusion prevention framework
platform: linux
category: security
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: fail2ban-client primary capability
    patterns:
      execute:
        description: Execute fail2ban-client command
        typical_use_cases:
        - use fail2ban-client
        - fail2ban-client command
        - intrusion prevention framework
        time_estimate_ms: '2000'
        cost_estimate: '3'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - linux
  - security
  - fail2ban-client
  documentation_url: https://docs.opsconductor.io/tools/fail2ban-client

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute fail2ban-client command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 2000
    expected_cost: 3
