# iptables - IPv4/IPv6 firewall administration
tool_name: iptables
version: '1.0'
description: IPv4/IPv6 firewall administration
platform: linux
category: security
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: iptables primary capability
    patterns:
      execute:
        description: Execute iptables command
        typical_use_cases:
        - use iptables
        - iptables command
        - ipv4/ipv6 firewall administration
        time_estimate_ms: '2000'
        cost_estimate: '3'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - linux
  - security
  - iptables
  documentation_url: https://docs.opsconductor.io/tools/iptables
