# netstat - Display network connections and statistics
tool_name: netstat
execution_location: automation-service
version: '1.0'
description: Display network connections and statistics
platform: linux
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  network_monitoring:
    description: network_monitoring capability
    patterns:
      list_connections:
        description: list_connections pattern
        typical_use_cases:
        - list connections
        - network stats
        - open ports
        time_estimate_ms: '400'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - linux
  - network
  - netstat
  documentation_url: https://docs.opsconductor.io/tools/netstat

# === EXAMPLES ===
examples:
  - name: "List Connections"
    description: "list_connections pattern"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 400
    expected_cost: 1
