# ps - Process status utility
tool_name: "ps"
version: "1.0"
description: "Report detailed process status, resource usage, and system information"
platform: "linux"
category: "process-management"

defaults:
  accuracy_level: "real-time"
  freshness: "live"
  data_source: "procfs"

capabilities:
  process_monitoring:
    description: "Monitor and list system processes with detailed resource usage and state information"
    
    patterns:
      list_all_processes:
        description: "List all running processes with comprehensive details"
        
        typical_use_cases:
          - "list all processes"
          - "show running processes"
          - "ps aux"
          - "view process list"
          - "check what's running"
          - "process inventory"
        
        time_estimate_ms: "200 + 0.5 * num_processes"
        cost_estimate: "1"
        complexity_score: 0.1
        
        scope: "exhaustive"
        completeness: "complete"
        
        limitations:
          - "Snapshot in time, not continuous monitoring"
          - "Process list may change between reads"
          - "Some process info requires root privileges"
          - "Kernel threads shown but have limited info"
        
        policy:
          max_cost: 2
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.95
          completeness: 1.0
        
        required_inputs:
          - name: "host"
            type: "string"
            description: "Target host where ps command will be executed"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
            examples:
              - "web-server-01"
              - "192.168.1.100"
              - "app.example.com"
        
        optional_inputs:
          - name: "format"
            type: "string"
            description: "Output format style"
            default: "aux"
            allowed_values:
              - "aux"
              - "ef"
              - "full"
              - "long"
              - "custom"
          - name: "sort_by"
            type: "string"
            description: "Sort processes by specified field"
            default: "pid"
            allowed_values:
              - "pid"
              - "cpu"
              - "memory"
              - "time"
              - "command"
          - name: "show_threads"
            type: "boolean"
            description: "Show individual threads (ps -L)"
            default: "false"
          - name: "show_environment"
            type: "boolean"
            description: "Include environment variables (ps e)"
            default: "false"
        
        expected_outputs:
          - name: "processes"
            type: "array"
            description: "List of processes with PID, user, CPU%, memory%, state, command"
          - name: "total_count"
            type: "integer"
            description: "Total number of processes"
          - name: "summary"
            type: "object"
            description: "Summary statistics (total processes, running, sleeping, zombie)"
      
      find_process:
        description: "Find specific process by name, PID, or user"
        
        typical_use_cases:
          - "find process by name"
          - "search for specific process"
          - "check if process is running"
          - "get process details"
          - "find process by PID"
          - "list user processes"
        
        time_estimate_ms: "150 + 0.3 * num_processes"
        cost_estimate: "1"
        complexity_score: 0.1
        
        scope: "single_item"
        completeness: "complete"
        
        limitations:
          - "Process name matching is substring match"
          - "May return multiple matches"
          - "Command line truncation in some formats"
        
        policy:
          max_cost: 2
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.95
          completeness: 1.0
        
        required_inputs:
          - name: "host"
            type: "string"
            description: "Target host for process search"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
            examples:
              - "app-server-01"
              - "192.168.1.50"
        
        optional_inputs:
          - name: "process_name"
            type: "string"
            description: "Process name or command to search for (partial match supported)"
            default: ""
            examples:
              - "nginx"
              - "python"
              - "java"
              - "postgres"
          - name: "pid"
            type: "integer"
            description: "Specific process ID to query"
            default: null
            examples:
              - 1234
              - 5678
          - name: "user"
            type: "string"
            description: "Filter processes by username or UID"
            default: ""
            examples:
              - "www-data"
              - "root"
              - "1000"
          - name: "exact_match"
            type: "boolean"
            description: "Require exact process name match (not substring)"
            default: "false"
        
        expected_outputs:
          - name: "matches"
            type: "array"
            description: "Matching processes with full details"
          - name: "match_count"
            type: "integer"
            description: "Number of matching processes found"
          - name: "is_running"
            type: "boolean"
            description: "Whether any matching process was found"
      
      process_tree:
        description: "Show process hierarchy and parent-child relationships"
        
        typical_use_cases:
          - "show process tree"
          - "view parent child processes"
          - "process hierarchy"
          - "see process relationships"
          - "trace process ancestry"
        
        time_estimate_ms: "300 + 1 * num_processes"
        cost_estimate: "1"
        complexity_score: 0.2
        
        scope: "exhaustive"
        completeness: "complete"
        
        limitations:
          - "Tree structure may be complex for many processes"
          - "Orphaned processes shown under init/systemd"
          - "Thread relationships not shown in tree"
        
        policy:
          max_cost: 2
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        
        preference_match:
          speed: 0.9
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        
        required_inputs:
          - name: "host"
            type: "string"
            description: "Target host for process tree display"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
        
        optional_inputs:
          - name: "root_pid"
            type: "integer"
            description: "Show tree starting from specific PID (omit for full tree from init)"
            default: null
            examples:
              - 1
              - 1234
          - name: "show_threads"
            type: "boolean"
            description: "Include threads in tree view"
            default: "false"
          - name: "show_arguments"
            type: "boolean"
            description: "Show command line arguments in tree"
            default: "true"
        
        expected_outputs:
          - name: "tree"
            type: "object"
            description: "Hierarchical process tree structure"
          - name: "depth"
            type: "integer"
            description: "Maximum depth of process tree"
      
      resource_usage:
        description: "Show processes sorted by resource consumption (CPU, memory)"
        
        typical_use_cases:
          - "find high CPU processes"
          - "show memory hogs"
          - "top CPU consumers"
          - "processes using most resources"
          - "performance troubleshooting"
        
        time_estimate_ms: "250 + 0.8 * num_processes"
        cost_estimate: "1"
        complexity_score: 0.2
        
        scope: "exhaustive"
        completeness: "complete"
        
        limitations:
          - "CPU% is average since process start, not instantaneous"
          - "Memory includes shared libraries (may overcount)"
          - "Short-lived processes may be missed"
        
        policy:
          max_cost: 3
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        
        required_inputs:
          - name: "host"
            type: "string"
            description: "Target host for resource analysis"
            validation: "^[a-zA-Z0-9][a-zA-Z0-9.-]*$|^\\d{1,3}(\\.\\d{1,3}){3}$"
          - name: "sort_by"
            type: "string"
            description: "Resource metric to sort by"
            allowed_values:
              - "cpu"
              - "memory"
              - "time"
            examples:
              - "cpu"
              - "memory"
        
        optional_inputs:
          - name: "top_n"
            type: "integer"
            description: "Return only top N processes"
            default: 10
            examples:
              - 5
              - 10
              - 20
          - name: "min_cpu_percent"
            type: "number"
            description: "Filter processes using at least this much CPU%"
            default: 0.0
            examples:
              - 1.0
              - 5.0
          - name: "min_memory_mb"
            type: "integer"
            description: "Filter processes using at least this much memory (MB)"
            default: 0
            examples:
              - 100
              - 500
        
        expected_outputs:
          - name: "top_processes"
            type: "array"
            description: "Processes sorted by resource usage"
          - name: "total_cpu_percent"
            type: "number"
            description: "Combined CPU usage of all processes"
          - name: "total_memory_mb"
            type: "integer"
            description: "Combined memory usage in MB"

dependencies:
  - name: "procfs"
    type: "filesystem"
    required: true
  - name: "procps"
    type: "package"
    required: true
    version: ">=3.3"

metadata:
  author: "OpsConductor Team"
  created: "2025-01-15"
  updated: "2025-01-15"
  tags:
    - "linux"
    - "process"
    - "monitoring"
    - "performance"
    - "system"
  documentation_url: "https://man7.org/linux/man-pages/man1/ps.1.html"
  related_tools:
    - "top"
    - "htop"
    - "pgrep"
    - "kill"

examples:
  - name: "List all processes"
    description: "Show all running processes with CPU and memory usage"
    inputs:
      host: "app-server-01"
      format: "aux"
      sort_by: "cpu"
    expected_time_ms: 300
    expected_cost: 1
  
  - name: "Find nginx processes"
    description: "Check if nginx is running and get process details"
    inputs:
      host: "web-server-01"
      process_name: "nginx"
      exact_match: false
    expected_time_ms: 200
    expected_cost: 1
  
  - name: "Show process tree"
    description: "Display hierarchical process tree for troubleshooting"
    inputs:
      host: "app-server-01"
      show_arguments: true
      show_threads: false
    expected_time_ms: 400
    expected_cost: 1
  
  - name: "Find memory hogs"
    description: "Identify top 10 processes consuming most memory"
    inputs:
      host: "db-server-01"
      sort_by: "memory"
      top_n: 10
      min_memory_mb: 100
    expected_time_ms: 350
    expected_cost: 1
  
  - name: "Check specific PID"
    description: "Get detailed information about specific process"
    inputs:
      host: "app-server-01"
      pid: 1234
    expected_time_ms: 150
    expected_cost: 1
  
  - name: "List user processes"
    description: "Show all processes owned by specific user"
    inputs:
      host: "web-server-01"
      user: "www-data"
      format: "full"
    expected_time_ms: 250
    expected_cost: 1