# systemd-timer - Systemd timer units
tool_name: systemd-timer
execution_location: automation-service
version: '1.0'
description: Systemd timer units
platform: linux
category: automation
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: systemd-timer primary capability
    patterns:
      execute:
        description: Execute systemd-timer command
        typical_use_cases:
        - use systemd-timer
        - systemd-timer command
        - systemd timer units
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - linux
  - automation
  - systemd-timer
  documentation_url: https://docs.opsconductor.io/tools/systemd-timer

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute systemd-timer command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 500
    expected_cost: 1
