# uname - Display system information
tool_name: uname
version: '1.0'
description: Display system information
platform: linux
category: system
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  system_info:
    description: system_info capability
    patterns:
      get_system_info:
        description: get_system_info pattern
        typical_use_cases:
        - system info
        - kernel version
        - os info
        time_estimate_ms: '100'
        cost_estimate: '1'
        complexity_score: 0.1
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - linux
  - system
  - uname
  documentation_url: https://docs.opsconductor.io/tools/uname

# === EXAMPLES ===
examples:
  - name: "Get System Info"
    description: "get_system_info pattern"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 100
    expected_cost: 1
