# node_exporter - Prometheus exporter for hardware and OS metrics
tool_name: node_exporter
execution_location: automation-service
version: '1.0'
description: Prometheus exporter for hardware and OS metrics
platform: monitoring
category: monitoring
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: node_exporter primary capability
    patterns:
      execute:
        description: Execute node_exporter command
        typical_use_cases:
        - use node_exporter
        - node_exporter command
        - prometheus exporter for hardware and os metrics
        time_estimate_ms: 1000 + 5 * N
        cost_estimate: ceil(N / 100)
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - monitoring
  - monitoring
  - node_exporter
  documentation_url: https://docs.opsconductor.io/tools/node_exporter

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute node_exporter command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 1000
    expected_cost: 1
