# rsyslog - Rocket-fast system for log processing
tool_name: rsyslog
version: '1.0'
description: Rocket-fast system for log processing
platform: monitoring
category: monitoring
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: rsyslog primary capability
    patterns:
      execute:
        description: Execute rsyslog command
        typical_use_cases:
        - use rsyslog
        - rsyslog command
        - rocket-fast system for log processing
        time_estimate_ms: 1000 + 5 * N
        cost_estimate: ceil(N / 100)
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - monitoring
  - monitoring
  - rsyslog
  documentation_url: https://docs.opsconductor.io/tools/rsyslog
