#!/usr/bin/env python3
"""
Seed script to create 20 sample assets with realistic data
"""
import asyncio
import httpx
from typing import List, Dict, Any

# Asset Service URL
ASSET_SERVICE_URL = "http://localhost:8002"

# Sample assets with realistic data
SAMPLE_ASSETS: List[Dict[str, Any]] = [
    {
        "name": "Production Web Server 01",
        "hostname": "web-prod-01.acme.com",
        "ip_address": "10.0.1.10",
        "description": "Primary production web server hosting customer-facing applications",
        "tags": ["production", "web", "critical", "load-balanced"],
        "device_type": "server",
        "hardware_make": "Dell",
        "hardware_model": "PowerEdge R750",
        "serial_number": "SN-DELL-R750-001234",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 101",
        "rack_position": "U15-U17",
        "rack_location": "Rack A-12",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "DevOps Team",
        "support_contact": "devops@acme.com",
        "contract_number": "DELL-SUP-2024-001",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "ssh_key",
        "username": "admin",
        "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA...\n-----END OPENSSH PRIVATE KEY-----",
        "secondary_service_type": "http",
        "secondary_port": 80,
        "notes": "Primary web server, part of load balancer pool. Requires 24/7 monitoring."
    },
    {
        "name": "Database Master Server",
        "hostname": "db-master-01.acme.com",
        "ip_address": "10.0.2.20",
        "description": "PostgreSQL master database server for production workloads",
        "tags": ["production", "database", "critical", "postgresql"],
        "device_type": "server",
        "hardware_make": "HPE",
        "hardware_model": "ProLiant DL380 Gen10",
        "serial_number": "SN-HPE-DL380-005678",
        "os_type": "linux",
        "os_version": "Red Hat Enterprise Linux 8.8",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 102",
        "rack_position": "U20-U22",
        "rack_location": "Rack B-05",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Database Team",
        "support_contact": "dba@acme.com",
        "contract_number": "HPE-SUP-2024-002",
        "service_type": "database",
        "port": 5432,
        "is_secure": True,
        "credential_type": "password",
        "username": "postgres",
        "password": "SecureP@ssw0rd123!",
        "database_type": "postgresql",
        "database_name": "production_db",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "dbadmin",
        "secondary_password": "AdminP@ss456!",
        "notes": "Master database with streaming replication to db-replica-01. Daily backups at 2 AM UTC."
    },
    {
        "name": "Development API Server",
        "hostname": "api-dev-01.acme.com",
        "ip_address": "10.0.3.30",
        "description": "Development environment API server for testing new features",
        "tags": ["development", "api", "testing"],
        "device_type": "server",
        "hardware_make": "Lenovo",
        "hardware_model": "ThinkSystem SR650",
        "serial_number": "SN-LEN-SR650-009012",
        "os_type": "linux",
        "os_version": "Ubuntu 20.04.6 LTS",
        "physical_address": "456 Tech Park Boulevard, Austin, TX 78701",
        "data_center": "DC-AUS-01",
        "building": "Building C",
        "room": "Dev Lab 201",
        "rack_position": "U10-U12",
        "rack_location": "Rack C-03",
        "gps_coordinates": "30.2672,-97.7431",
        "status": "active",
        "environment": "development",
        "criticality": "low",
        "owner": "API Development Team",
        "support_contact": "api-dev@acme.com",
        "contract_number": "LEN-SUP-2024-003",
        "service_type": "http",
        "port": 8080,
        "is_secure": False,
        "credential_type": "api_key",
        "api_key": "dev_api_key_abc123xyz789",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "developer",
        "secondary_password": "DevP@ss789!",
        "notes": "Development server, can be rebooted without notice. Auto-deploys from dev branch."
    },
    {
        "name": "Network Core Switch 01",
        "hostname": "switch-core-01.acme.com",
        "ip_address": "10.0.0.1",
        "description": "Core network switch for primary data center",
        "tags": ["network", "switch", "critical", "core"],
        "device_type": "network",
        "hardware_make": "Cisco",
        "hardware_model": "Catalyst 9500-48Y4C",
        "serial_number": "SN-CISCO-C9500-012345",
        "os_type": "other",
        "os_version": "IOS XE 17.9.3",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Network Operations Center",
        "rack_position": "U35-U37",
        "rack_location": "Rack N-01",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Network Operations",
        "support_contact": "netops@acme.com",
        "contract_number": "CISCO-SUP-2024-004",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "password",
        "username": "netadmin",
        "password": "NetSecure!2024",
        "secondary_service_type": "telnet",
        "secondary_port": 23,
        "notes": "Core switch with redundant power supplies. Firmware updates require change control approval."
    },
    {
        "name": "Backup Storage Array",
        "hostname": "storage-backup-01.acme.com",
        "ip_address": "10.0.4.40",
        "description": "Primary backup storage array with 500TB capacity",
        "tags": ["storage", "backup", "critical"],
        "device_type": "storage",
        "hardware_make": "NetApp",
        "hardware_model": "FAS8300",
        "serial_number": "SN-NETAPP-FAS8300-067890",
        "os_type": "other",
        "os_version": "ONTAP 9.12.1",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building B",
        "room": "Storage Room 105",
        "rack_position": "U1-U8",
        "rack_location": "Rack S-10",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Storage Team",
        "support_contact": "storage@acme.com",
        "contract_number": "NETAPP-SUP-2024-005",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "password",
        "username": "storageadmin",
        "password": "Storage!Secure2024",
        "secondary_service_type": "http",
        "secondary_port": 443,
        "notes": "Backup storage with daily snapshots. Retention policy: 30 days local, 90 days offsite."
    },
    {
        "name": "Windows Domain Controller",
        "hostname": "dc-01.acme.local",
        "ip_address": "10.0.5.50",
        "description": "Primary Active Directory domain controller",
        "tags": ["windows", "domain-controller", "critical", "active-directory"],
        "device_type": "server",
        "hardware_make": "Dell",
        "hardware_model": "PowerEdge R640",
        "serial_number": "SN-DELL-R640-023456",
        "os_type": "windows",
        "os_version": "Windows Server 2022 Standard",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 101",
        "rack_position": "U25-U27",
        "rack_location": "Rack A-08",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Windows Team",
        "support_contact": "winadmin@acme.com",
        "contract_number": "DELL-SUP-2024-006",
        "service_type": "winrm",
        "port": 5985,
        "is_secure": False,
        "credential_type": "password",
        "username": "ACME\\Administrator",
        "password": "WinAdmin!2024",
        "domain": "acme.local",
        "secondary_service_type": "rdp",
        "secondary_port": 3389,
        "notes": "Primary DC with FSMO roles. Replicates to dc-02. Monthly Windows updates on second Sunday."
    },
    {
        "name": "Staging Web Server",
        "hostname": "web-staging-01.acme.com",
        "ip_address": "10.0.6.60",
        "description": "Staging environment web server for pre-production testing",
        "tags": ["staging", "web", "testing"],
        "device_type": "server",
        "hardware_make": "Supermicro",
        "hardware_model": "SuperServer 6029P-TRT",
        "serial_number": "SN-SUPER-6029P-034567",
        "os_type": "linux",
        "os_version": "Debian 11.7",
        "physical_address": "456 Tech Park Boulevard, Austin, TX 78701",
        "data_center": "DC-AUS-01",
        "building": "Building C",
        "room": "Server Room 202",
        "rack_position": "U15-U17",
        "rack_location": "Rack C-07",
        "gps_coordinates": "30.2672,-97.7431",
        "status": "active",
        "environment": "staging",
        "criticality": "medium",
        "owner": "QA Team",
        "support_contact": "qa@acme.com",
        "contract_number": "SUPER-SUP-2024-007",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "ssh_key",
        "username": "deploy",
        "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA...\n-----END OPENSSH PRIVATE KEY-----",
        "secondary_service_type": "http",
        "secondary_port": 8080,
        "notes": "Staging server mirrors production configuration. Deploy window: weekdays 9 AM - 5 PM."
    },
    {
        "name": "Monitoring Server",
        "hostname": "monitor-01.acme.com",
        "ip_address": "10.0.7.70",
        "description": "Central monitoring and alerting server running Prometheus and Grafana",
        "tags": ["monitoring", "prometheus", "grafana", "critical"],
        "device_type": "server",
        "hardware_make": "Dell",
        "hardware_model": "PowerEdge R440",
        "serial_number": "SN-DELL-R440-045678",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 103",
        "rack_position": "U30-U32",
        "rack_location": "Rack A-15",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "SRE Team",
        "support_contact": "sre@acme.com",
        "contract_number": "DELL-SUP-2024-008",
        "service_type": "http",
        "port": 9090,
        "is_secure": False,
        "credential_type": "bearer_token",
        "bearer_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "monitor",
        "secondary_password": "Monitor!Pass2024",
        "notes": "Prometheus retention: 30 days. Grafana dashboards for all services. Alert to PagerDuty."
    },
    {
        "name": "Load Balancer 01",
        "hostname": "lb-prod-01.acme.com",
        "ip_address": "10.0.8.80",
        "description": "HAProxy load balancer for production web traffic",
        "tags": ["load-balancer", "production", "critical", "haproxy"],
        "device_type": "network",
        "hardware_make": "F5",
        "hardware_model": "BIG-IP i5800",
        "serial_number": "SN-F5-I5800-056789",
        "os_type": "other",
        "os_version": "TMOS 16.1.3",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Network Operations Center",
        "rack_position": "U40-U42",
        "rack_location": "Rack N-03",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Network Operations",
        "support_contact": "netops@acme.com",
        "contract_number": "F5-SUP-2024-009",
        "service_type": "http",
        "port": 443,
        "is_secure": True,
        "credential_type": "password",
        "username": "lbadmin",
        "password": "LoadBalancer!2024",
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAKZ...\n-----END CERTIFICATE-----",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "notes": "Active-passive HA pair with lb-prod-02. SSL termination for all web traffic."
    },
    {
        "name": "CI/CD Build Server",
        "hostname": "jenkins-01.acme.com",
        "ip_address": "10.0.9.90",
        "description": "Jenkins CI/CD server for automated builds and deployments",
        "tags": ["cicd", "jenkins", "automation", "development"],
        "device_type": "server",
        "hardware_make": "HPE",
        "hardware_model": "ProLiant DL360 Gen10",
        "serial_number": "SN-HPE-DL360-067890",
        "os_type": "linux",
        "os_version": "CentOS Stream 9",
        "physical_address": "456 Tech Park Boulevard, Austin, TX 78701",
        "data_center": "DC-AUS-01",
        "building": "Building C",
        "room": "Dev Lab 203",
        "rack_position": "U20-U22",
        "rack_location": "Rack C-10",
        "gps_coordinates": "30.2672,-97.7431",
        "status": "active",
        "environment": "development",
        "criticality": "medium",
        "owner": "DevOps Team",
        "support_contact": "devops@acme.com",
        "contract_number": "HPE-SUP-2024-010",
        "service_type": "http",
        "port": 8080,
        "is_secure": False,
        "credential_type": "password",
        "username": "jenkins",
        "password": "Jenkins!Build2024",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "jenkins",
        "secondary_password": "Jenkins!SSH2024",
        "notes": "Jenkins master with 5 build agents. Automated nightly builds. Backup config daily."
    },
    {
        "name": "Email Server",
        "hostname": "mail-01.acme.com",
        "ip_address": "10.0.10.100",
        "description": "Primary email server running Postfix and Dovecot",
        "tags": ["email", "postfix", "dovecot", "critical"],
        "device_type": "server",
        "hardware_make": "Dell",
        "hardware_model": "PowerEdge R540",
        "serial_number": "SN-DELL-R540-078901",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 104",
        "rack_position": "U35-U37",
        "rack_location": "Rack A-18",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "IT Operations",
        "support_contact": "itops@acme.com",
        "contract_number": "DELL-SUP-2024-011",
        "service_type": "smtp",
        "port": 25,
        "is_secure": False,
        "credential_type": "password",
        "username": "mailadmin",
        "password": "Mail!Secure2024",
        "secondary_service_type": "imap",
        "secondary_port": 993,
        "secondary_username": "mailadmin",
        "secondary_password": "Mail!Secure2024",
        "notes": "Primary mail server with spam filtering. Daily mail queue monitoring. TLS required."
    },
    {
        "name": "VPN Gateway",
        "hostname": "vpn-01.acme.com",
        "ip_address": "203.0.113.10",
        "description": "OpenVPN gateway for remote employee access",
        "tags": ["vpn", "security", "remote-access", "critical"],
        "device_type": "network",
        "hardware_make": "Cisco",
        "hardware_model": "ASA 5525-X",
        "serial_number": "SN-CISCO-ASA5525-089012",
        "os_type": "other",
        "os_version": "ASA 9.18(2)",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Network Operations Center",
        "rack_position": "U45-U47",
        "rack_location": "Rack N-05",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Security Team",
        "support_contact": "security@acme.com",
        "contract_number": "CISCO-SUP-2024-012",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "password",
        "username": "vpnadmin",
        "password": "VPN!Secure2024",
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAKZ...\n-----END CERTIFICATE-----",
        "secondary_service_type": "http",
        "secondary_port": 443,
        "notes": "VPN gateway with 2FA required. Max 500 concurrent connections. Logs to SIEM."
    },
    {
        "name": "Container Registry",
        "hostname": "registry-01.acme.com",
        "ip_address": "10.0.11.110",
        "description": "Private Docker registry for container images",
        "tags": ["docker", "registry", "containers", "development"],
        "device_type": "server",
        "hardware_make": "Lenovo",
        "hardware_model": "ThinkSystem SR630",
        "serial_number": "SN-LEN-SR630-090123",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "456 Tech Park Boulevard, Austin, TX 78701",
        "data_center": "DC-AUS-01",
        "building": "Building C",
        "room": "Server Room 204",
        "rack_position": "U25-U27",
        "rack_location": "Rack C-12",
        "gps_coordinates": "30.2672,-97.7431",
        "status": "active",
        "environment": "production",
        "criticality": "medium",
        "owner": "DevOps Team",
        "support_contact": "devops@acme.com",
        "contract_number": "LEN-SUP-2024-013",
        "service_type": "http",
        "port": 5000,
        "is_secure": True,
        "credential_type": "password",
        "username": "registry",
        "password": "Registry!2024",
        "certificate": "-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAKZ...\n-----END CERTIFICATE-----",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "registry",
        "secondary_password": "Registry!SSH2024",
        "notes": "Private Docker registry with image scanning. Retention: 90 days for dev, indefinite for prod."
    },
    {
        "name": "Firewall 01",
        "hostname": "fw-01.acme.com",
        "ip_address": "203.0.113.1",
        "description": "Perimeter firewall for data center security",
        "tags": ["firewall", "security", "critical", "perimeter"],
        "device_type": "network",
        "hardware_make": "Palo Alto",
        "hardware_model": "PA-5220",
        "serial_number": "SN-PA-5220-101234",
        "os_type": "other",
        "os_version": "PAN-OS 11.0.2",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Network Operations Center",
        "rack_position": "U50-U52",
        "rack_location": "Rack N-01",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Security Team",
        "support_contact": "security@acme.com",
        "contract_number": "PA-SUP-2024-014",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "password",
        "username": "fwadmin",
        "password": "Firewall!2024",
        "secondary_service_type": "http",
        "secondary_port": 443,
        "notes": "Primary perimeter firewall. HA pair with fw-02. Change control required for rule changes."
    },
    {
        "name": "DNS Server 01",
        "hostname": "dns-01.acme.com",
        "ip_address": "10.0.12.120",
        "description": "Primary internal DNS server running BIND",
        "tags": ["dns", "bind", "critical", "infrastructure"],
        "device_type": "server",
        "hardware_make": "Supermicro",
        "hardware_model": "SuperServer 5019P-MT",
        "serial_number": "SN-SUPER-5019P-112345",
        "os_type": "linux",
        "os_version": "Rocky Linux 9.2",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 105",
        "rack_position": "U40-U41",
        "rack_location": "Rack A-20",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Network Operations",
        "support_contact": "netops@acme.com",
        "contract_number": "SUPER-SUP-2024-015",
        "service_type": "dns",
        "port": 53,
        "is_secure": False,
        "credential_type": "password",
        "username": "dnsadmin",
        "password": "DNS!Secure2024",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "dnsadmin",
        "secondary_password": "DNS!SSH2024",
        "notes": "Primary DNS server with DNSSEC enabled. Replicates to dns-02. Zone transfers restricted."
    },
    {
        "name": "Kubernetes Master 01",
        "hostname": "k8s-master-01.acme.com",
        "ip_address": "10.0.13.130",
        "description": "Kubernetes control plane master node",
        "tags": ["kubernetes", "k8s", "orchestration", "critical"],
        "device_type": "server",
        "hardware_make": "Dell",
        "hardware_model": "PowerEdge R650",
        "serial_number": "SN-DELL-R650-123456",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "456 Tech Park Boulevard, Austin, TX 78701",
        "data_center": "DC-AUS-01",
        "building": "Building C",
        "room": "Server Room 205",
        "rack_position": "U30-U32",
        "rack_location": "Rack C-15",
        "gps_coordinates": "30.2672,-97.7431",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Platform Team",
        "support_contact": "platform@acme.com",
        "contract_number": "DELL-SUP-2024-016",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "ssh_key",
        "username": "k8sadmin",
        "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA...\n-----END OPENSSH PRIVATE KEY-----",
        "secondary_service_type": "http",
        "secondary_port": 6443,
        "notes": "K8s master node in HA cluster with k8s-master-02 and k8s-master-03. etcd backup daily."
    },
    {
        "name": "Log Aggregation Server",
        "hostname": "logs-01.acme.com",
        "ip_address": "10.0.14.140",
        "description": "Elasticsearch cluster for centralized logging",
        "tags": ["logging", "elasticsearch", "elk", "critical"],
        "device_type": "server",
        "hardware_make": "HPE",
        "hardware_model": "ProLiant DL385 Gen10",
        "serial_number": "SN-HPE-DL385-134567",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building B",
        "room": "Server Room 106",
        "rack_position": "U10-U13",
        "rack_location": "Rack B-08",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "SRE Team",
        "support_contact": "sre@acme.com",
        "contract_number": "HPE-SUP-2024-017",
        "service_type": "http",
        "port": 9200,
        "is_secure": True,
        "credential_type": "password",
        "username": "elastic",
        "password": "Elastic!2024",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "elastic",
        "secondary_password": "Elastic!SSH2024",
        "notes": "Elasticsearch cluster with 3 nodes. Log retention: 30 days hot, 90 days warm, 1 year cold."
    },
    {
        "name": "FTP Server",
        "hostname": "ftp-01.acme.com",
        "ip_address": "10.0.15.150",
        "description": "SFTP server for secure file transfers with partners",
        "tags": ["ftp", "sftp", "file-transfer", "medium"],
        "device_type": "server",
        "hardware_make": "Lenovo",
        "hardware_model": "ThinkSystem SR530",
        "serial_number": "SN-LEN-SR530-145678",
        "os_type": "linux",
        "os_version": "Debian 11.7",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 107",
        "rack_position": "U45-U47",
        "rack_location": "Rack A-22",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "medium",
        "owner": "IT Operations",
        "support_contact": "itops@acme.com",
        "contract_number": "LEN-SUP-2024-018",
        "service_type": "sftp",
        "port": 22,
        "is_secure": True,
        "credential_type": "ssh_key",
        "username": "ftpadmin",
        "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA...\n-----END OPENSSH PRIVATE KEY-----",
        "ftp_type": "sftp",
        "secondary_service_type": "ftp",
        "secondary_port": 21,
        "secondary_username": "ftpuser",
        "secondary_password": "FTP!User2024",
        "notes": "SFTP server for partner file exchanges. Chroot jails per partner. Files auto-archived after 7 days."
    },
    {
        "name": "Test Automation Server",
        "hostname": "test-auto-01.acme.com",
        "ip_address": "10.0.16.160",
        "description": "Selenium Grid for automated browser testing",
        "tags": ["testing", "selenium", "automation", "qa"],
        "device_type": "server",
        "hardware_make": "Dell",
        "hardware_model": "PowerEdge R340",
        "serial_number": "SN-DELL-R340-156789",
        "os_type": "linux",
        "os_version": "Ubuntu 20.04.6 LTS",
        "physical_address": "456 Tech Park Boulevard, Austin, TX 78701",
        "data_center": "DC-AUS-01",
        "building": "Building C",
        "room": "QA Lab 206",
        "rack_position": "U35-U37",
        "rack_location": "Rack C-18",
        "gps_coordinates": "30.2672,-97.7431",
        "status": "active",
        "environment": "testing",
        "criticality": "low",
        "owner": "QA Team",
        "support_contact": "qa@acme.com",
        "contract_number": "DELL-SUP-2024-019",
        "service_type": "http",
        "port": 4444,
        "is_secure": False,
        "credential_type": "password",
        "username": "selenium",
        "password": "Selenium!2024",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "selenium",
        "secondary_password": "Selenium!SSH2024",
        "notes": "Selenium Grid with Chrome, Firefox, and Edge nodes. Automated test runs nightly at 1 AM."
    },
    {
        "name": "Cache Server",
        "hostname": "cache-01.acme.com",
        "ip_address": "10.0.17.170",
        "description": "Redis cache cluster for application performance",
        "tags": ["cache", "redis", "performance", "critical"],
        "device_type": "server",
        "hardware_make": "Supermicro",
        "hardware_model": "SuperServer 1029P-MTR",
        "serial_number": "SN-SUPER-1029P-167890",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "123 Data Center Drive, San Jose, CA 95110",
        "data_center": "DC-SJC-01",
        "building": "Building A",
        "room": "Server Room 108",
        "rack_position": "U50-U52",
        "rack_location": "Rack A-25",
        "gps_coordinates": "37.3382,-121.8863",
        "status": "active",
        "environment": "production",
        "criticality": "critical",
        "owner": "Backend Team",
        "support_contact": "backend@acme.com",
        "contract_number": "SUPER-SUP-2024-020",
        "service_type": "redis",
        "port": 6379,
        "is_secure": True,
        "credential_type": "password",
        "password": "Redis!Secure2024",
        "secondary_service_type": "ssh",
        "secondary_port": 22,
        "secondary_username": "redis",
        "secondary_password": "Redis!SSH2024",
        "notes": "Redis cluster with 6 nodes (3 masters, 3 replicas). Persistence enabled. Max memory: 64GB."
    },
    {
        "name": "Linux Test Server",
        "hostname": "linux-test-01.acme.com",
        "ip_address": "192.168.50.12",
        "description": "Linux test server for comprehensive tool validation and testing",
        "tags": ["testing", "linux", "validation", "tools"],
        "device_type": "server",
        "hardware_make": "VMware",
        "hardware_model": "Virtual Machine",
        "serial_number": "VM-TEST-192-168-50-12",
        "os_type": "linux",
        "os_version": "Ubuntu 22.04.3 LTS",
        "physical_address": "Test Lab Environment",
        "data_center": "TEST-LAB-01",
        "building": "Virtual Infrastructure",
        "room": "Test Environment",
        "rack_position": "Virtual",
        "rack_location": "VM-RACK-01",
        "gps_coordinates": "0.0000,0.0000",
        "status": "active",
        "environment": "testing",
        "criticality": "low",
        "owner": "QA Team",
        "support_contact": "qa-linux@acme.com",
        "contract_number": "TEST-VM-2024-001",
        "service_type": "ssh",
        "port": 22,
        "is_secure": True,
        "credential_type": "password",
        "username": "testuser",
        "password": "TestLinux!2024",
        "secondary_service_type": "http",
        "secondary_port": 80,
        "notes": "Linux test server for comprehensive tool validation. Safe for testing all Linux commands and operations."
    }
]


async def create_assets():
    """Create sample assets via Asset Service API"""
    async with httpx.AsyncClient(timeout=30.0) as client:
        print(f"Creating {len(SAMPLE_ASSETS)} sample assets...")
        print("-" * 80)
        
        created_count = 0
        failed_count = 0
        
        for idx, asset_data in enumerate(SAMPLE_ASSETS, 1):
            try:
                response = await client.post(
                    f"{ASSET_SERVICE_URL}/",
                    json=asset_data
                )
                
                if response.status_code == 200:
                    result = response.json()
                    created_count += 1
                    print(f"✓ [{idx}/{len(SAMPLE_ASSETS)}] Created: {asset_data['name']} (ID: {result.get('id')})")
                else:
                    failed_count += 1
                    print(f"✗ [{idx}/{len(SAMPLE_ASSETS)}] Failed: {asset_data['name']} - Status: {response.status_code}")
                    print(f"  Error: {response.text}")
                    
            except Exception as e:
                failed_count += 1
                print(f"✗ [{idx}/{len(SAMPLE_ASSETS)}] Error creating {asset_data['name']}: {str(e)}")
        
        print("-" * 80)
        print(f"\nSummary:")
        print(f"  Created: {created_count}")
        print(f"  Failed:  {failed_count}")
        print(f"  Total:   {len(SAMPLE_ASSETS)}")


if __name__ == "__main__":
    asyncio.run(create_assets())