# OpsConductor Network Analytics Remote Probe Configuration

# Central analyzer connection settings
central_analyzer:
  # URL of the central OpsConductor analyzer
  url: "https://your-opsconductor-server.com:3006"
  
  # Optional API key for authentication
  api_key: null
  
  # SSL verification (set to false for self-signed certificates)
  verify_ssl: true

# Probe identification
probe:
  # Unique identifier for this probe
  id: "remote-probe-001"
  
  # Human-readable name
  name: "Remote Network Probe"
  
  # Location description
  location: "Remote Office - Building A"

# Heartbeat settings
heartbeat_interval: 30  # seconds

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  
  # Log file path (platform-specific defaults will be used if not specified)
  file: null
  
  # Maximum log file size in MB
  max_size: 10
  
  # Number of backup log files to keep
  backup_count: 5

# Network interfaces to monitor
# Leave empty to auto-detect all available interfaces
# Specify interface names to limit monitoring
interfaces: []
  # - "eth0"
  # - "wlan0"
  # - "Ethernet"

# Packet capture settings
capture:
  # Default capture duration in seconds
  default_duration: 60
  
  # Maximum capture duration in seconds
  max_duration: 3600
  
  # Default packet count limit (0 = no limit)
  default_packet_limit: 1000
  
  # Maximum packet count limit
  max_packet_limit: 100000
  
  # Temporary directory for capture files
  temp_dir: null  # Uses system default if not specified

# Security settings
security:
  # Allowed source IPs for remote commands (empty = allow all)
  allowed_sources: []
    # - "192.168.1.0/24"
    # - "10.0.0.0/8"
  
  # Enable/disable remote packet capture
  allow_remote_capture: true
  
  # Enable/disable interface monitoring
  allow_interface_monitoring: true

# Advanced settings
advanced:
  # Connection timeout in seconds
  connection_timeout: 10
  
  # Retry attempts for failed connections
  retry_attempts: 3
  
  # Retry delay in seconds
  retry_delay: 5
  
  # Enable debug mode
  debug: false