key: linux.grep
name: Linux Grep
short_desc: Search text in files on Linux using grep with regex support.
platform:
  - linux
tags:
  - diagnostics
  - search
  - text
meta:
  cmd: "grep -Rni '{{pattern}}' '{{path}}'"