# docker-compose - Multi-container Docker applications
tool_name: docker-compose
version: '1.0'
description: Multi-container Docker applications
platform: container
category: container
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: docker-compose primary capability
    patterns:
      execute:
        description: Execute docker-compose command
        typical_use_cases:
        - use docker-compose
        - docker-compose command
        - multi-container docker applications
        time_estimate_ms: '1000'
        cost_estimate: '2'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - container
  - container
  - docker-compose
  documentation_url: https://docs.opsconductor.io/tools/docker-compose
