# kubectl-describe - Show detailed resource information
tool_name: kubectl-describe
version: '1.0'
description: Show detailed resource information
platform: kubernetes
category: container
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: kubectl-describe primary capability
    patterns:
      execute:
        description: Execute kubectl-describe command
        typical_use_cases:
        - use kubectl-describe
        - kubectl-describe command
        - show detailed resource information
        time_estimate_ms: '1000'
        cost_estimate: '2'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - kubernetes
  - container
  - kubectl-describe
  documentation_url: https://docs.opsconductor.io/tools/kubectl-describe

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute kubectl-describe command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 1000
    expected_cost: 2
