# Axis VAPIX Recording - Manage recorded video via VAPIX API
tool_name: Axis-VAPIX-Recording
execution_location: network-service
version: '1.0'
description: |
  Manage recorded video on Axis camera via VAPIX API.
  Supports listing, exporting, and deleting recordings.
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/record
  auth_type: digest
  method: GET
capabilities:
  list_recordings:
    description: List available recordings
    patterns:
      get_recording_list:
        description: Get list of all recordings on storage
        typical_use_cases:
        - list recordings
        - show recorded videos
        - get recording list
        - view recordings
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: multiple_items
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: disk_id
          type: string
          description: Storage disk identifier (SD_DISK or NetworkShare)
          validation: ^(SD_DISK|NetworkShare)$
          default: "SD_DISK"
        api_parameters:
          diskid: "{disk_id}"
        example_request: "GET http://{host}/axis-cgi/record/list.cgi?diskid={disk_id}"
  export_recording:
    description: Export recording as video file
    patterns:
      download_recording:
        description: Download recording for specified time range
        typical_use_cases:
        - export recording
        - download video
        - get recording file
        - save recording
        time_estimate_ms: '5000'
        cost_estimate: '3'
        complexity_score: 0.5
        scope: single_item
        completeness: complete
        policy:
          max_cost: 15
          requires_approval: false
          production_safe: true
          max_execution_time: 300
        preference_match:
          speed: 0.7
          accuracy: 0.9
          cost: 0.7
          complexity: 0.6
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: disk_id
          type: string
          description: Storage disk identifier
          validation: ^(SD_DISK|NetworkShare)$
          default: "SD_DISK"
        - name: start_time
          type: string
          description: |
            Recording start time in ISO 8601 format.
            
            FORMAT: YYYY-MM-DDTHH:MM:SSZ
            
            EXAMPLES:
            - "2025-01-15T10:00:00Z"
            - "2025-01-15T14:30:00Z"
          validation: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
        - name: end_time
          type: string
          description: |
            Recording end time in ISO 8601 format.
            
            FORMAT: YYYY-MM-DDTHH:MM:SSZ
            
            EXAMPLES:
            - "2025-01-15T11:00:00Z"
            - "2025-01-15T15:30:00Z"
          validation: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
        api_parameters:
          diskid: "{disk_id}"
          starttime: "{start_time}"
          stoptime: "{end_time}"
        example_request: "GET http://{host}/axis-cgi/record/export/exportrecording.cgi?diskid={disk_id}&starttime={start_time}&stoptime={end_time}"
  delete_recording:
    description: Delete recordings from storage
    patterns:
      remove_recording:
        description: Delete recording for specified time range
        typical_use_cases:
        - delete recording
        - remove video
        - clear recordings
        - free up space
        time_estimate_ms: '2000'
        cost_estimate: '2'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 30
        preference_match:
          speed: 0.85
          accuracy: 0.9
          cost: 0.85
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: disk_id
          type: string
          description: Storage disk identifier
          validation: ^(SD_DISK|NetworkShare)$
          default: "SD_DISK"
        - name: recording_id
          type: string
          description: Recording identifier to delete
          validation: .+
        api_parameters:
          diskid: "{disk_id}"
          recordingid: "{recording_id}"
        example_request: "GET http://{host}/axis-cgi/record/remove.cgi?diskid={disk_id}&recordingid={recording_id}"
metadata:
  author: OpsConductor Team
  created: '2025-01-15'
  updated: '2025-01-15'
  tags:
  - axis
  - vapix
  - camera
  - recording
  - video
  - export
  - playback
  documentation_url: https://developer.axis.com/vapix/network-video/edge-storage-api/
  api_reference: https://developer.axis.com/vapix/
  notes: |
    Axis VAPIX Recording Management API
    
    RECORDING FORMATS:
    - Matroska (MKV): Default format
    - MP4: Alternative format
    
    TIME FORMAT:
    - ISO 8601: YYYY-MM-DDTHH:MM:SSZ
    - UTC timezone
    
    EXAMPLES:
    
    1. List all recordings:
       GET http://192.168.1.100/axis-cgi/record/list.cgi?diskid=SD_DISK
    
    2. Export recording (1 hour):
       GET http://192.168.1.100/axis-cgi/record/export/exportrecording.cgi
       ?diskid=SD_DISK&starttime=2025-01-15T10:00:00Z&stoptime=2025-01-15T11:00:00Z
    
    3. Delete recording:
       GET http://192.168.1.100/axis-cgi/record/remove.cgi?diskid=SD_DISK&recordingid=12345

# === EXAMPLES ===
examples:
  - name: "Get Recording List"
    description: "Get list of all recordings on storage"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      disk_id: "example_disk_id"
    expected_time_ms: 1000
    expected_cost: 1
  - name: "Download Recording"
    description: "Download recording for specified time range"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      disk_id: "example_disk_id"
      start_time: "example_start_time"
      end_time: "example_end_time"
    expected_time_ms: 5000
    expected_cost: 3
  - name: "Remove Recording"
    description: "Delete recording for specified time range"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      disk_id: "example_disk_id"
      recording_id: "example_recording_id"
    expected_time_ms: 2000
    expected_cost: 2
