# Axis VAPIX Edge Storage - Control SD card/NAS storage via VAPIX API
tool_name: Axis-VAPIX-Edge-Storage
version: '1.0'
description: |
  Control Axis camera edge storage (SD card/NAS) via VAPIX API.
  Supports recording control and storage management.
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/record
  auth_type: digest
  method: GET
capabilities:
  start_recording:
    description: Start continuous or event-based recording
    patterns:
      start_continuous_recording:
        description: Start continuous recording to edge storage
        typical_use_cases:
        - start recording
        - begin continuous recording
        - record to sd card
        - enable recording
        time_estimate_ms: '2000'
        cost_estimate: '2'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        preference_match:
          speed: 0.85
          accuracy: 0.9
          cost: 0.85
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: disk_id
          type: string
          description: |
            Storage disk identifier.
            
            VALUE MEANINGS:
            - "SD_DISK": SD card storage
            - "NetworkShare": Network storage (NAS)
            
            EXAMPLES:
            - "SD_DISK" - Record to SD card
            - "NetworkShare" - Record to NAS
          validation: ^(SD_DISK|NetworkShare)$
          default: "SD_DISK"
        api_parameters:
          diskid: "{disk_id}"
          action: "start"
        example_request: "GET http://{host}/axis-cgi/record/continuous/start.cgi?diskid={disk_id}"
  stop_recording:
    description: Stop ongoing recording
    patterns:
      stop_continuous_recording:
        description: Stop continuous recording
        typical_use_cases:
        - stop recording
        - end recording
        - disable recording
        time_estimate_ms: '2000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: disk_id
          type: string
          description: Storage disk identifier (SD_DISK or NetworkShare)
          validation: ^(SD_DISK|NetworkShare)$
          default: "SD_DISK"
        api_parameters:
          diskid: "{disk_id}"
          action: "stop"
        example_request: "GET http://{host}/axis-cgi/record/continuous/stop.cgi?diskid={disk_id}"
  get_storage_status:
    description: Get storage disk status and capacity
    patterns:
      check_disk_status:
        description: Check SD card or NAS storage status
        typical_use_cases:
        - check storage status
        - get disk space
        - check sd card capacity
        - storage health check
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 3
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        api_parameters:
          action: "list"
        example_request: "GET http://{host}/axis-cgi/disks/list.cgi?action=list"
metadata:
  author: OpsConductor Team
  created: '2025-01-15'
  updated: '2025-01-15'
  tags:
  - axis
  - vapix
  - camera
  - storage
  - recording
  - sd card
  - nas
  - edge storage
  documentation_url: https://developer.axis.com/vapix/network-video/edge-storage-api/
  api_reference: https://developer.axis.com/vapix/
  notes: |
    Axis VAPIX Edge Storage API
    
    STORAGE TYPES:
    - SD_DISK: SD card storage (local)
    - NetworkShare: Network storage (NAS/CIFS/NFS)
    
    RECORDING MODES:
    - Continuous: Record continuously
    - Event-based: Record on motion/trigger
    - Scheduled: Record on schedule
    
    STORAGE MANAGEMENT:
    - Automatic overwrite when full
    - Retention policies
    - Storage health monitoring
    
    EXAMPLES:
    
    1. Start continuous recording to SD card:
       GET http://192.168.1.100/axis-cgi/record/continuous/start.cgi?diskid=SD_DISK
    
    2. Stop recording:
       GET http://192.168.1.100/axis-cgi/record/continuous/stop.cgi?diskid=SD_DISK
    
    3. Check storage status:
       GET http://192.168.1.100/axis-cgi/disks/list.cgi?action=list
    
    4. Get recording status:
       GET http://192.168.1.100/axis-cgi/record/status.cgi

# === EXAMPLES ===
examples:
  - name: "Start Continuous Recording"
    description: "Start continuous recording to edge storage"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      disk_id: "example_disk_id"
    expected_time_ms: 2000
    expected_cost: 2
  - name: "Stop Continuous Recording"
    description: "Stop continuous recording"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      disk_id: "example_disk_id"
    expected_time_ms: 2000
    expected_cost: 1
  - name: "Check Disk Status"
    description: "Check SD card or NAS storage status"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
    expected_time_ms: 1000
    expected_cost: 1
