# Axis VAPIX Stream Profiles - Manage video stream profiles via VAPIX API
tool_name: Axis-VAPIX-Stream-Profiles
version: '1.0'
description: |
  Manage Axis camera video stream profiles via VAPIX API.
  Supports listing, creating, and managing predefined stream configurations.
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/streamprofile.cgi
  auth_type: digest
  method: GET
capabilities:
  list_profiles:
    description: List all available stream profiles
    patterns:
      get_all_profiles:
        description: Get list of all configured stream profiles
        typical_use_cases:
        - list stream profiles
        - get available profiles
        - show stream configurations
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: multiple_items
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: |
            Axis camera IP address or hostname.
            
            EXAMPLES:
            - "192.168.1.100"
            - "camera-profiles.local"
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        api_parameters:
          action: "list"
        example_request: "GET http://{host}/axis-cgi/streamprofile.cgi?action=list"
  get_profile:
    description: Get specific stream profile details
    patterns:
      get_profile_details:
        description: Get configuration details for a specific profile
        typical_use_cases:
        - get profile details
        - check profile settings
        - view profile configuration
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 3
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: profile_name
          type: string
          description: |
            Name of the stream profile to retrieve.
            
            COMMON PROFILES:
            - "High": High quality profile
            - "Medium": Medium quality profile
            - "Low": Low quality profile
            - "Custom": User-defined profiles
            
            EXAMPLES:
            - "High" - High quality settings
            - "Mobile" - Mobile-optimized settings
          validation: ^[a-zA-Z0-9_-]+$
        api_parameters:
          action: "get"
          profilename: "{profile_name}"
        example_request: "GET http://{host}/axis-cgi/streamprofile.cgi?action=get&profilename={profile_name}"
  create_profile:
    description: Create new stream profile
    patterns:
      add_custom_profile:
        description: Create custom stream profile with specific settings
        typical_use_cases:
        - create stream profile
        - add custom profile
        - define new stream configuration
        time_estimate_ms: '2000'
        cost_estimate: '2'
        complexity_score: 0.6
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        preference_match:
          speed: 0.8
          accuracy: 0.85
          cost: 0.8
          complexity: 0.5
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: profile_name
          type: string
          description: |
            Name for the new stream profile.
            
            EXAMPLES:
            - "LowBandwidth"
            - "HighQuality"
            - "Mobile"
          validation: ^[a-zA-Z0-9_-]+$
        - name: resolution
          type: string
          description: |
            Video resolution for the profile.
            
            COMMON RESOLUTIONS:
            - "1920x1080": Full HD
            - "1280x720": HD
            - "640x480": VGA
            
            EXAMPLES:
            - "1920x1080" - Full HD
            - "640x480" - Low bandwidth
          validation: ^\d{3,4}x\d{3,4}$
        - name: fps
          type: integer
          description: |
            Frames per second.
            
            COMMON VALUES:
            - 30: Smooth motion
            - 15: Moderate bandwidth
            - 5: Low bandwidth
            
            EXAMPLES:
            - 30 - Smooth motion
            - 15 - Balanced
            - 5 - Low bandwidth
          validation: ^[1-9]|[1-5][0-9]|60$
        - name: codec
          type: string
          description: |
            Video codec.
            
            OPTIONS:
            - "h264": H.264/AVC
            - "h265": H.265/HEVC
            - "mjpeg": Motion JPEG
            
            EXAMPLES:
            - "h264" - Standard
            - "h265" - High efficiency
          validation: ^(h264|h265|mjpeg)$
        api_parameters:
          action: "add"
          profilename: "{profile_name}"
          resolution: "{resolution}"
          fps: "{fps}"
          videocodec: "{codec}"
        example_request: "GET http://{host}/axis-cgi/streamprofile.cgi?action=add&profilename={profile_name}&resolution={resolution}&fps={fps}&videocodec={codec}"
  delete_profile:
    description: Delete stream profile
    patterns:
      remove_profile:
        description: Remove custom stream profile
        typical_use_cases:
        - delete stream profile
        - remove profile
        - delete custom configuration
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: true
          production_safe: false
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: profile_name
          type: string
          description: Name of the profile to delete
          validation: ^[a-zA-Z0-9_-]+$
        api_parameters:
          action: "remove"
          profilename: "{profile_name}"
        example_request: "GET http://{host}/axis-cgi/streamprofile.cgi?action=remove&profilename={profile_name}"
metadata:
  author: OpsConductor Team
  created: '2025-01-15'
  updated: '2025-01-15'
  tags:
  - axis
  - vapix
  - camera
  - stream profiles
  - video configuration
  - presets
  documentation_url: https://developer.axis.com/vapix/network-video/stream-profiles/
  api_reference: https://developer.axis.com/vapix/
  notes: |
    Axis VAPIX Stream Profiles API
    
    STREAM PROFILES:
    - Predefined video stream configurations
    - Include resolution, FPS, codec, bitrate
    - Simplify stream management
    - Can be referenced by name in RTSP URLs
    
    DEFAULT PROFILES:
    - High: High quality (1080p, 30fps, H.264)
    - Medium: Medium quality (720p, 15fps, H.264)
    - Low: Low quality (480p, 5fps, H.264)
    
    PROFILE PARAMETERS:
    - Resolution: Video resolution
    - FPS: Frames per second
    - Codec: Video codec (H.264, H.265, MJPEG)
    - Bitrate: Target bitrate
    - GOP length: Group of pictures length
    - Compression: Compression level
    
    USING PROFILES IN RTSP:
    rtsp://<host>/axis-media/media.amp?streamprofile=<profile_name>
    
    EXAMPLES:
    
    1. List all profiles:
       GET http://192.168.1.100/axis-cgi/streamprofile.cgi?action=list
    
    2. Get "High" profile details:
       GET http://192.168.1.100/axis-cgi/streamprofile.cgi?action=get&profilename=High
    
    3. Create custom "Mobile" profile:
       GET http://192.168.1.100/axis-cgi/streamprofile.cgi?action=add
       &profilename=Mobile&resolution=640x480&fps=15&videocodec=h264
    
    4. Delete custom profile:
       GET http://192.168.1.100/axis-cgi/streamprofile.cgi?action=remove&profilename=Mobile
    
    5. Use profile in RTSP URL:
       rtsp://192.168.1.100/axis-media/media.amp?streamprofile=Mobile
    
    BEST PRACTICES:
    - Create profiles for common use cases
    - Use descriptive profile names
    - Test profiles before deployment
    - Document profile purposes
    - Don't delete default profiles

# === EXAMPLES ===
examples:
  - name: "Get All Profiles"
    description: "Get list of all configured stream profiles"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
    expected_time_ms: 1000
    expected_cost: 1
  - name: "Get Profile Details"
    description: "Get configuration details for a specific profile"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      profile_name: "example_name"
    expected_time_ms: 500
    expected_cost: 1
  - name: "Add Custom Profile"
    description: "Create custom stream profile with specific settings"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      profile_name: "example_name"
      resolution: "example_resolution"
      fps: 100
      codec: "example_codec"
    expected_time_ms: 2000
    expected_cost: 2
  - name: "Remove Profile"
    description: "Remove custom stream profile"
    inputs:
      host: "192.168.1.100"
      username: "admin"
      password: "secure_password"
      profile_name: "example_name"
    expected_time_ms: 1000
    expected_cost: 1
