# asset-query - Query asset inventory
tool_name: asset-query
execution_location: asset-service
version: '1.1'
description: Query and filter asset inventory by various criteria
platform: custom
category: asset
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  asset_management:
    description: Query and filter asset inventory
    patterns:
      execute:
        description: Query assets with optional filters
        typical_use_cases:
        - query asset inventory
        - count assets
        - list assets
        - filter assets by OS
        - find Windows 10 machines
        - search for specific hostname
        - get assets by tag
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        optional_inputs:
        - name: asset_id
          type: integer
          description: Specific asset ID to retrieve
        - name: hostname
          type: string
          description: Filter by hostname (partial match supported)
        - name: os_type
          type: string
          description: Filter by OS type (exact match - e.g., "windows", "linux")
        - name: os_version
          type: string
          description: Filter by OS version (partial match - e.g., "10", "Ubuntu 22.04")
        - name: status
          type: string
          description: Filter by status (e.g., "active", "inactive")
        - name: environment
          type: string
          description: Filter by environment (e.g., "production", "staging")
        - name: tags
          type: array
          description: Filter by tags (can be string or array of strings)
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - custom
  - asset
  - asset-query
  documentation_url: https://docs.opsconductor.io/tools/asset-query

# === EXAMPLES ===
examples:
  - name: "Query all assets"
    description: "Get all assets in inventory"
    inputs: {}
    expected_time_ms: 500
    expected_cost: 1
  
  - name: "Find Windows 10 machines"
    description: "Query assets with Windows 10 OS"
    inputs:
      os_type: "windows"
      os_version: "10"
    expected_time_ms: 500
    expected_cost: 1
  
  - name: "Find by hostname"
    description: "Search for assets by hostname"
    inputs:
      hostname: "web-server"
    expected_time_ms: 500
    expected_cost: 1
  
  - name: "Find by tags"
    description: "Query assets with specific tags"
    inputs:
      tags: ["production", "critical"]
    expected_time_ms: 500
    expected_cost: 1
  
  - name: "Find active Linux servers"
    description: "Query active Linux assets"
    inputs:
      os_type: "linux"
      status: "active"
    expected_time_ms: 500
    expected_cost: 1
