global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'opsconductor-production'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Multi-Brain AI System Metrics
  - job_name: 'ai-brain-production'
    static_configs:
      - targets: ['ai-brain-production:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Database Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis Metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Nginx Metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-production:9113']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ChromaDB Health Check
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb-production:8000']
    metrics_path: '/api/v1/heartbeat'
    scrape_interval: 30s

  # Ollama LLM Server
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama-production:11434']
    metrics_path: '/api/tags'
    scrape_interval: 60s