# Axis VAPIX Overlay - Add text/image overlays to video via VAPIX API
tool_name: Axis-VAPIX-Overlay
version: '1.0'
description: |
  Add text and image overlays to Axis camera video via VAPIX API.
  Supports dynamic text, timestamps, and custom images.
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/param.cgi
  auth_type: digest
  method: GET
capabilities:
  add_text_overlay:
    description: Add text overlay to video stream
    patterns:
      create_text_overlay:
        description: Create text overlay with custom text
        typical_use_cases:
        - add text overlay
        - show text on video
        - add timestamp
        - add camera name
        time_estimate_ms: '1500'
        cost_estimate: '2'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        preference_match:
          speed: 0.85
          accuracy: 0.9
          cost: 0.85
          complexity: 0.7
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: overlay_text
          type: string
          description: |
            Text to display in overlay.
            
            SPECIAL MODIFIERS:
            - #D: Current date
            - #T: Current time
            - #F: Frame number
            
            EXAMPLES:
            - "Camera 1 - Entrance"
            - "Date: #D Time: #T"
            - "Lobby Camera"
          validation: .+
        - name: position
          type: string
          description: |
            Overlay position on screen.
            
            VALUE MEANINGS:
            - "top": Top center
            - "bottom": Bottom center
            - "topleft": Top left corner
            - "topright": Top right corner
            - "bottomleft": Bottom left corner
            - "bottomright": Bottom right corner
            
            EXAMPLES:
            - "top" - Top center
            - "bottomleft" - Bottom left
          validation: ^(top|bottom|topleft|topright|bottomleft|bottomright)$
          default: "top"
        api_parameters:
          action: "update"
          Overlay.O0.Enabled: "yes"
          Overlay.O0.Text: "{overlay_text}"
          Overlay.O0.Position: "{position}"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&Overlay.O0.Enabled=yes&Overlay.O0.Text={overlay_text}&Overlay.O0.Position={position}"
  remove_overlay:
    description: Remove text overlay from video
    patterns:
      disable_overlay:
        description: Disable text overlay
        typical_use_cases:
        - remove overlay
        - disable text overlay
        - hide overlay
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with operator or administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        api_parameters:
          action: "update"
          Overlay.O0.Enabled: "no"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&Overlay.O0.Enabled=no"
  get_overlay_settings:
    description: Get current overlay configuration
    patterns:
      list_overlays:
        description: List all overlay settings
        typical_use_cases:
        - get overlay settings
        - list overlays
        - check overlay status
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: multiple_items
        completeness: complete
        policy:
          max_cost: 3
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        api_parameters:
          action: "list"
          group: "Overlay"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=list&group=Overlay"
metadata:
  author: OpsConductor Team
  created: '2025-01-15'
  updated: '2025-01-15'
  tags:
  - axis
  - vapix
  - camera
  - overlay
  - text
  - timestamp
  - osd
  documentation_url: https://developer.axis.com/vapix/network-video/overlay-api/
  api_reference: https://developer.axis.com/vapix/
  notes: |
    Axis VAPIX Overlay API
    
    OVERLAY TYPES:
    - Text overlays: Static or dynamic text
    - Image overlays: Custom images/logos
    - Timestamp overlays: Date/time display
    
    TEXT MODIFIERS:
    - #D: Current date (YYYY-MM-DD)
    - #T: Current time (HH:MM:SS)
    - #F: Frame number
    - #Z: Zoom level
    - #P: Pan position
    - #t: Tilt position
    
    OVERLAY POSITIONS:
    - top, bottom: Centered
    - topleft, topright: Corners
    - bottomleft, bottomright: Corners
    
    MULTIPLE OVERLAYS:
    - O0, O1, O2, etc. for multiple overlays
    - Each overlay can have different text and position
    
    EXAMPLES:
    
    1. Add camera name overlay:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update
       &Overlay.O0.Enabled=yes&Overlay.O0.Text=Camera%201%20-%20Entrance
       &Overlay.O0.Position=top
    
    2. Add timestamp overlay:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update
       &Overlay.O0.Enabled=yes&Overlay.O0.Text=%23D%20%23T
       &Overlay.O0.Position=bottomleft
    
    3. Remove overlay:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update
       &Overlay.O0.Enabled=no
    
    4. List all overlays:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=list&group=Overlay