# Axis VAPIX Privacy Mask - Configure privacy masks via VAPIX API
tool_name: Axis-VAPIX-Privacy-Mask
version: '1.0'
description: |
  Configure privacy masks on Axis camera via VAPIX API.
  Supports creating, modifying, and removing privacy masks to block sensitive areas.
platform: network
category: network
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
  protocol: http
  path: /axis-cgi/param.cgi
  auth_type: digest
  method: GET
capabilities:
  create_privacy_mask:
    description: Create privacy mask to block area in video
    patterns:
      add_rectangular_mask:
        description: Add rectangular privacy mask
        typical_use_cases:
        - add privacy mask
        - block area in video
        - create privacy zone
        - mask sensitive area
        time_estimate_ms: '2000'
        cost_estimate: '2'
        complexity_score: 0.5
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 15
        preference_match:
          speed: 0.85
          accuracy: 0.9
          cost: 0.85
          complexity: 0.6
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: mask_name
          type: string
          description: |
            Name for the privacy mask.
            
            EXAMPLES:
            - "window_mask"
            - "neighbor_property"
            - "privacy_zone_1"
          validation: ^[a-zA-Z0-9_-]+$
        - name: x_position
          type: integer
          description: |
            X coordinate of mask top-left corner (0-10000).
            
            VALUE MEANINGS:
            - 0: Left edge
            - 5000: Center
            - 10000: Right edge
            
            EXAMPLES:
            - 0 - Left edge
            - 2500 - 25% from left
            - 5000 - Center
          validation: ^([0-9]{1,4}|10000)$
        - name: y_position
          type: integer
          description: |
            Y coordinate of mask top-left corner (0-10000).
            
            VALUE MEANINGS:
            - 0: Top edge
            - 5000: Center
            - 10000: Bottom edge
            
            EXAMPLES:
            - 0 - Top edge
            - 2500 - 25% from top
            - 5000 - Center
          validation: ^([0-9]{1,4}|10000)$
        - name: width
          type: integer
          description: |
            Width of mask (0-10000).
            
            EXAMPLES:
            - 1000 - 10% of image width
            - 2500 - 25% of image width
            - 5000 - 50% of image width
          validation: ^([0-9]{1,4}|10000)$
        - name: height
          type: integer
          description: |
            Height of mask (0-10000).
            
            EXAMPLES:
            - 1000 - 10% of image height
            - 2500 - 25% of image height
            - 5000 - 50% of image height
          validation: ^([0-9]{1,4}|10000)$
        api_parameters:
          action: "update"
          PrivacyMask.P0.Enabled: "yes"
          PrivacyMask.P0.Name: "{mask_name}"
          PrivacyMask.P0.X: "{x_position}"
          PrivacyMask.P0.Y: "{y_position}"
          PrivacyMask.P0.Width: "{width}"
          PrivacyMask.P0.Height: "{height}"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&PrivacyMask.P0.Enabled=yes&PrivacyMask.P0.Name={mask_name}&PrivacyMask.P0.X={x_position}&PrivacyMask.P0.Y={y_position}&PrivacyMask.P0.Width={width}&PrivacyMask.P0.Height={height}"
  remove_privacy_mask:
    description: Remove privacy mask
    patterns:
      disable_mask:
        description: Disable privacy mask
        typical_use_cases:
        - remove privacy mask
        - disable mask
        - delete privacy zone
        time_estimate_ms: '1000'
        cost_estimate: '1'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 5
          requires_approval: true
          production_safe: false
          max_execution_time: 10
        preference_match:
          speed: 0.9
          accuracy: 0.95
          cost: 0.9
          complexity: 0.8
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username with administrator privileges
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        - name: mask_number
          type: integer
          description: |
            Privacy mask number to remove (0-N).
            
            EXAMPLES:
            - 0 - First mask (P0)
            - 1 - Second mask (P1)
          validation: ^[0-9]$
          default: 0
        api_parameters:
          action: "update"
          PrivacyMask.P{mask_number}.Enabled: "no"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=update&PrivacyMask.P{mask_number}.Enabled=no"
  list_privacy_masks:
    description: List all privacy masks
    patterns:
      get_all_masks:
        description: Get list of all configured privacy masks
        typical_use_cases:
        - list privacy masks
        - get privacy zones
        - show masks
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: multiple_items
        completeness: complete
        policy:
          max_cost: 3
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        preference_match:
          speed: 0.95
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        required_inputs:
        - name: host
          type: string
          description: Axis camera IP address or hostname
          validation: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$|^[a-zA-Z0-9.-]+$
        - name: username
          type: string
          description: Camera API username
          validation: .+
        - name: password
          type: string
          description: Camera API password
          validation: .+
        api_parameters:
          action: "list"
          group: "PrivacyMask"
        example_request: "GET http://{host}/axis-cgi/param.cgi?action=list&group=PrivacyMask"
metadata:
  author: OpsConductor Team
  created: '2025-01-15'
  updated: '2025-01-15'
  tags:
  - axis
  - vapix
  - camera
  - privacy
  - mask
  - privacy zone
  - gdpr
  documentation_url: https://developer.axis.com/vapix/network-video/overlay-api/#privacy-mask-api
  api_reference: https://developer.axis.com/vapix/
  notes: |
    Axis VAPIX Privacy Mask API
    
    PRIVACY MASK TYPES:
    - Rectangular: Simple rectangular masks
    - Polygon: Complex shaped masks (advanced)
    
    COORDINATE SYSTEM:
    - X, Y: Top-left corner position (0-10000)
    - Width, Height: Mask dimensions (0-10000)
    - Coordinates are normalized (0-10000 = 0-100%)
    
    MASK APPEARANCE:
    - Solid color (usually black or gray)
    - Permanently blocks area in video
    - Applied to all streams
    
    MULTIPLE MASKS:
    - P0, P1, P2, etc. for multiple masks
    - Maximum number depends on camera model
    
    COMMON USE CASES:
    - Block neighbor's windows
    - Hide sensitive areas (keypads, screens)
    - GDPR compliance (public areas)
    - Protect privacy in shared spaces
    
    EXAMPLES:
    
    1. Create mask covering top-left quarter:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update
       &PrivacyMask.P0.Enabled=yes&PrivacyMask.P0.Name=window_mask
       &PrivacyMask.P0.X=0&PrivacyMask.P0.Y=0
       &PrivacyMask.P0.Width=5000&PrivacyMask.P0.Height=5000
    
    2. Create mask in center:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update
       &PrivacyMask.P0.Enabled=yes&PrivacyMask.P0.Name=center_mask
       &PrivacyMask.P0.X=2500&PrivacyMask.P0.Y=2500
       &PrivacyMask.P0.Width=5000&PrivacyMask.P0.Height=5000
    
    3. Remove mask:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=update
       &PrivacyMask.P0.Enabled=no
    
    4. List all masks:
       GET http://192.168.1.100/axis-cgi/param.cgi?action=list&group=PrivacyMask
    
    BEST PRACTICES:
    - Test mask position with live view
    - Use descriptive mask names
    - Document mask purposes
    - Review masks periodically
    - Consider PTZ camera movement (masks are fixed)