FROM kong:3.4

# Copy configuration
COPY kong.yml /usr/local/kong/declarative/kong.yml

# Set permissions
USER root
RUN chown -R kong:kong /usr/local/kong/declarative/
USER kong

# Set environment variables
ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
ENV KONG_PROXY_ACCESS_LOG=/dev/stdout
ENV KONG_ADMIN_ACCESS_LOG=/dev/stdout
ENV KONG_PROXY_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_LISTEN=0.0.0.0:8001
ENV KONG_PROXY_LISTEN=0.0.0.0:8000

EXPOSE 8000 8001

CMD ["kong", "start"]