name: Add-Content
version: "1.0"
description: "Appends content to a file. Creates the file if it doesn't exist."
platform: windows
category: system
tags:
  - file
  - append
  - content
  - text
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: false