name: Compress-Archive
version: "1.0"
description: "Creates a compressed archive (ZIP file) from specified files and directories."
platform: windows
category: system
tags:
  - archive
  - zip
  - compress
  - backup
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: false