tool:
  name: Copy-Item
  version: "1.0"
  description: "Copies files or directories on a Windows system"
  platform: windows
  category: system
  
  capability:
    name: file_copy
    description: "Copy files and directories"
    
  pattern:
    name: copy_file
    description: "Copy file, copy folder, copy directory, duplicate file, cp command"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: source
      type: string
      required: true
      description: "Source path to copy from"
    - name: destination
      type: string
      required: true
      description: "Destination path to copy to"
    - name: recurse
      type: boolean
      required: false
      description: "Copy directories recursively"
    - name: force
      type: boolean
      required: false
      description: "Overwrite existing files"
      
  policy:
    approval_required: true
    production_safe: false
    timeout_seconds: 300