name: Expand-Archive
version: "1.0"
description: "Extracts files from a compressed archive (ZIP file) to a specified destination."
platform: windows
category: system
tags:
  - archive
  - zip
  - extract
  - decompress
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: false