name: ForEach-Object
version: "1.0"
description: "Performs an operation on each item in a collection of input objects. Essential PowerShell pipeline cmdlet."
platform: windows
category: system
tags:
  - pipeline
  - loop
  - iterate
  - objects
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: false