name: Get-NetIPConfiguration
version: "1.0"
description: "Gets network configuration including IP addresses, DNS servers, and default gateways. PowerShell alternative to ipconfig."
platform: windows
category: network
tags:
  - network
  - ip
  - configuration
  - dns
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: true