# Get-ChildItem - List directory contents on Windows
tool_name: Get-ChildItem
execution_location: automation-service
version: '1.0'
description: List files and directories on Windows systems
platform: windows
category: filesystem
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  directory_listing:
    description: List directory contents
    patterns:
      list_directory:
        description: List files and folders in a directory
        typical_use_cases:
        - list directory contents
        - show files in folder
        - browse directory
        - view folder contents
        - dir command
        - ls command
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.1
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.9
          accuracy: 0.9
          cost: 0.9
          complexity: 0.9
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host IP or hostname
          validation: .*
        - name: path
          type: string
          description: Directory path to list
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-16'
  updated: '2025-10-16'
  tags:
  - windows
  - filesystem
  - directory
  - get-childitem
  - ls
  - dir
  documentation_url: https://docs.opsconductor.io/tools/get-childitem

# === EXAMPLES ===
examples:
  - name: "List Windows Directory"
    description: "list_directory pattern"
    inputs:
      host: "192.168.1.100"
      path: "C:\\Windows"
    expected_time_ms: 500
    expected_cost: 1
  - name: "List Program Files"
    description: "list_directory pattern"
    inputs:
      host: "192.168.1.100"
      path: "C:\\Program Files"
    expected_time_ms: 500
    expected_cost: 1