tool:
  name: Get-Item
  version: "1.0"
  description: "Gets file or directory properties on a Windows system"
  platform: windows
  category: system
  
  capability:
    name: item_properties
    description: "Get file and directory properties"
    
  pattern:
    name: get_properties
    description: "Get file properties, file info, directory info, stat command"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: path
      type: string
      required: true
      description: "Path to the file or directory"
      
  policy:
    approval_required: false
    production_safe: true
    timeout_seconds: 60