# Get-ADGroupMember - Query AD group membership
tool_name: Get-ADGroupMember
version: '1.0'
description: Query AD group membership
platform: windows
category: security
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: Get-ADGroupMember primary capability
    patterns:
      execute:
        description: Execute Get-ADGroupMember command
        typical_use_cases:
        - use get-adgroupmember
        - get-adgroupmember command
        - query ad group membership
        time_estimate_ms: '2000'
        cost_estimate: '3'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - security
  - get-adgroupmember
  documentation_url: https://docs.opsconductor.io/tools/get-adgroupmember

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute Get-ADGroupMember command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 2000
    expected_cost: 3
