# Get-WmiObject - Query WMI for system information
tool_name: Get-WmiObject
version: '1.0'
description: Query WMI for system information
platform: windows
category: system
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  system_info:
    description: system_info capability
    patterns:
      query_wmi:
        description: query_wmi pattern
        typical_use_cases:
        - get system info
        - query hardware
        - wmi query
        time_estimate_ms: '800'
        cost_estimate: '2'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - system
  - get-wmiobject
  documentation_url: https://docs.opsconductor.io/tools/get-wmiobject
