# Get-Process - List and manage Windows processes
tool_name: Get-Process
version: '1.0'
description: List and manage Windows processes
platform: windows
category: system
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  process_management:
    description: process_management capability
    patterns:
      list_processes:
        description: list_processes pattern
        typical_use_cases:
        - list processes
        - show processes
        - get process info
        time_estimate_ms: '300'
        cost_estimate: '1'
        complexity_score: 0.1
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
      stop_process:
        description: stop_process pattern
        typical_use_cases:
        - stop process
        - kill process
        - terminate process
        time_estimate_ms: '500'
        cost_estimate: '2'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - system
  - get-process
  documentation_url: https://docs.opsconductor.io/tools/get-process
