# Get-Service - Query and manage Windows services
tool_name: Get-Service
version: '1.0'
description: Query and manage Windows services
platform: windows
category: system
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  service_management:
    description: service_management capability
    patterns:
      query_service:
        description: query_service pattern
        typical_use_cases:
        - check service status
        - list services
        - get service info
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
      start_service:
        description: start_service pattern
        typical_use_cases:
        - start service
        - enable service
        time_estimate_ms: '2000'
        cost_estimate: '2'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
      stop_service:
        description: stop_service pattern
        typical_use_cases:
        - stop service
        - disable service
        time_estimate_ms: '2000'
        cost_estimate: '2'
        complexity_score: 0.3
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - system
  - get-service
  documentation_url: https://docs.opsconductor.io/tools/get-service
