tool:
  name: Get-Content
  version: "1.0"
  description: "Reads the content of a file on a Windows system"
  platform: windows
  category: system
  
  capability:
    name: file_reading
    description: "Read and display file contents"
    
  pattern:
    name: read_file
    description: "Read file contents, view file, display file, cat file, type file, show file contents"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: path
      type: string
      required: true
      description: "Full path to the file to read"
    - name: tail
      type: integer
      required: false
      description: "Number of lines from the end of the file"
    - name: head
      type: integer
      required: false
      description: "Number of lines from the beginning of the file"
      
  policy:
    approval_required: false
    production_safe: true
    timeout_seconds: 60