# Get-ComputerInfo - Get comprehensive computer information
tool_name: Get-ComputerInfo
execution_location: automation-service
version: '1.0'
description: Get comprehensive computer information
platform: windows
category: system
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  system_info:
    description: system_info capability
    patterns:
      get_info:
        description: get_info pattern
        typical_use_cases:
        - get computer info
        - system details
        - hardware info
        time_estimate_ms: '1000'
        cost_estimate: '2'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - system
  - get-computerinfo
  documentation_url: https://docs.opsconductor.io/tools/get-computerinfo

# === EXAMPLES ===
examples:
  - name: "Get Info"
    description: "get_info pattern"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 1000
    expected_cost: 2
