# Get-Acl - Query file/folder permissions
tool_name: Get-Acl
version: '1.0'
description: Query file/folder permissions
platform: windows
category: security
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: Get-Acl primary capability
    patterns:
      execute:
        description: Execute Get-Acl command
        typical_use_cases:
        - use get-acl
        - get-acl command
        - query file/folder permissions
        time_estimate_ms: '2000'
        cost_estimate: '3'
        complexity_score: 0.4
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: false
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - security
  - get-acl
  documentation_url: https://docs.opsconductor.io/tools/get-acl
