# Invoke-Command - Execute commands on remote Windows hosts
tool_name: Invoke-Command
execution_location: automation-service
version: '1.0'
description: Execute commands on remote Windows hosts
platform: windows
category: automation
defaults:
  accuracy_level: real-time
  freshness: live
  data_source: direct
capabilities:
  primary_capability:
    description: Invoke-Command primary capability
    patterns:
      execute:
        description: Execute Invoke-Command command
        typical_use_cases:
        - use invoke-command
        - invoke-command command
        - execute commands on remote windows hosts
        time_estimate_ms: '500'
        cost_estimate: '1'
        complexity_score: 0.2
        scope: single_item
        completeness: complete
        policy:
          max_cost: 10
          requires_approval: false
          production_safe: true
          max_execution_time: 60
        preference_match:
          speed: 0.8
          accuracy: 0.9
          cost: 0.9
          complexity: 0.8
          completeness: 0.9
        required_inputs:
        - name: host
          type: string
          description: Target host
          validation: .*
metadata:
  author: OpsConductor Team
  created: '2025-10-03'
  updated: '2025-10-03'
  tags:
  - windows
  - automation
  - invoke-command
  documentation_url: https://docs.opsconductor.io/tools/invoke-command

# === EXAMPLES ===
examples:
  - name: "Execute"
    description: "Execute Invoke-Command command"
    inputs:
      host: "192.168.1.100"
    expected_time_ms: 500
    expected_cost: 1
