tool:
  name: Move-Item
  version: "1.0"
  description: "Moves or renames files or directories on a Windows system"
  platform: windows
  category: system
  
  capability:
    name: file_move
    description: "Move or rename files and directories"
    
  pattern:
    name: move_file
    description: "Move file, rename file, move folder, rename directory, mv command"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: source
      type: string
      required: true
      description: "Source path to move from"
    - name: destination
      type: string
      required: true
      description: "Destination path to move to"
    - name: force
      type: boolean
      required: false
      description: "Overwrite existing files"
      
  policy:
    approval_required: true
    production_safe: false
    timeout_seconds: 300