tool:
  name: New-Item
  version: "1.0"
  description: "Creates new files or directories on a Windows system"
  platform: windows
  category: system
  
  capability:
    name: file_creation
    description: "Create new files and directories"
    
  pattern:
    name: create_file
    description: "Create file, create folder, create directory, new file, mkdir command, touch command"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: path
      type: string
      required: true
      description: "Path where the item should be created"
    - name: item_type
      type: string
      required: true
      description: "Type of item to create (File or Directory)"
    - name: force
      type: boolean
      required: false
      description: "Create parent directories if they don't exist"
      
  policy:
    approval_required: true
    production_safe: false
    timeout_seconds: 60