# PowerShell - Windows automation and scripting
tool_name: "powershell"
version: "1.0"
description: "Windows PowerShell command execution and automation"
platform: "windows"
category: "automation"

defaults:
  accuracy_level: "real-time"
  freshness: "live"
  data_source: "windows_system"

capabilities:
  windows_automation:
    description: "Execute PowerShell commands and scripts"
    
    patterns:
      run_command:
        description: "Execute a PowerShell command"
        
        typical_use_cases:
          - "run powershell"
          - "execute command"
          - "windows command"
        
        time_estimate_ms: "1000 + command_complexity * 500"
        cost_estimate: "1"
        complexity_score: 0.3
        
        scope: "single_item"
        completeness: "complete"
        
        limitations:
          - "Requires PowerShell installed"
          - "May require admin privileges"
          - "Windows-only"
        
        policy:
          max_cost: 10
          requires_approval: true
          production_safe: true
          max_execution_time: 60
        
        preference_match:
          speed: 0.7
          accuracy: 1.0
          cost: 0.8
          complexity: 0.6
          completeness: 1.0
        
        required_inputs:
          - name: "command"
            type: "string"
            description: "PowerShell command to execute"
            validation: ".*"
        
        expected_outputs:
          - name: "stdout"
            type: "string"
            description: "Command standard output"
          - name: "stderr"
            type: "string"
            description: "Command error output"
          - name: "exit_code"
            type: "integer"
            description: "Command exit code"
  
  windows_service_management:
    description: "Manage Windows services"
    
    patterns:
      get_service:
        description: "Get service status"
        
        typical_use_cases:
          - "check service"
          - "service status"
          - "is service running"
        
        time_estimate_ms: "800"
        cost_estimate: "1"
        complexity_score: 0.2
        
        scope: "single_item"
        completeness: "complete"
        
        policy:
          max_cost: 5
          requires_approval: false
          production_safe: true
          max_execution_time: 10
        
        preference_match:
          speed: 0.9
          accuracy: 1.0
          cost: 0.95
          complexity: 0.9
          completeness: 1.0
        
        required_inputs:
          - name: "service_name"
            type: "string"
            description: "Name of the Windows service"
            validation: "^[a-zA-Z0-9_-]+$"
        
        expected_outputs:
          - name: "name"
            type: "string"
            description: "Service name"
          - name: "status"
            type: "string"
            description: "Service status (Running, Stopped, etc.)"
          - name: "start_type"
            type: "string"
            description: "Service start type (Automatic, Manual, Disabled)"

dependencies:
  - name: "powershell"
    type: "package"
    required: true
  - name: "windows_os"
    type: "platform"
    required: true

metadata:
  author: "OpsConductor Team"
  created: "2025-01-01"
  updated: "2025-01-01"
  tags:
    - "windows"
    - "powershell"
    - "automation"
  documentation_url: "https://docs.microsoft.com/en-us/powershell/"

examples:
  - name: "Check service status"
    description: "Get status of Windows Update service"
    inputs:
      service_name: "wuauserv"
    expected_time_ms: 800
    expected_cost: 1