tool:
  name: Restart-Service
  version: "1.0"
  description: "Restarts a Windows service"
  platform: windows
  category: system
  
  capability:
    name: service_restart
    description: "Restart Windows services"
    
  pattern:
    name: restart_service
    description: "Restart service, reboot service, reload service"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: service_name
      type: string
      required: true
      description: "Name of the service to restart"
    - name: force
      type: boolean
      required: false
      description: "Force restart the service"
      
  policy:
    approval_required: true
    production_safe: false
    timeout_seconds: 120