name: robocopy
version: "1.0"
description: "Robust file copy utility with advanced features like retry logic, mirroring, and multi-threading."
platform: windows
category: system
tags:
  - file
  - copy
  - backup
  - sync
metadata:
  execution_method: cmd
  requires_admin: false
  idempotent: false