name: Select-Object
version: "1.0"
description: "Selects specified properties of objects and can limit the number of objects. Essential PowerShell pipeline cmdlet."
platform: windows
category: system
tags:
  - pipeline
  - select
  - properties
  - objects
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: true