tool:
  name: Select-String
  version: "1.0"
  description: "Searches for text patterns in files on a Windows system"
  platform: windows
  category: system
  
  capability:
    name: text_search
    description: "Search for text patterns in files"
    
  pattern:
    name: search_text
    description: "Search text, find string, grep, findstr, search in file, search pattern"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: pattern
      type: string
      required: true
      description: "Text pattern or regex to search for"
    - name: path
      type: string
      required: true
      description: "File path or directory to search in"
    - name: recurse
      type: boolean
      required: false
      description: "Search recursively in subdirectories"
    - name: case_sensitive
      type: boolean
      required: false
      description: "Perform case-sensitive search"
      
  policy:
    approval_required: false
    production_safe: true
    timeout_seconds: 120