name: Set-Service
version: "1.0"
description: "Changes the properties of a service including startup type, display name, and description."
platform: windows
category: system
tags:
  - service
  - configure
  - startup
  - management
metadata:
  execution_method: powershell
  requires_admin: true
  idempotent: false