tool:
  name: Start-Service
  version: "1.0"
  description: "Starts a stopped Windows service"
  platform: windows
  category: system
  
  capability:
    name: service_start
    description: "Start Windows services"
    
  pattern:
    name: start_service
    description: "Start service, enable service, run service"
    
  inputs:
    - name: host
      type: string
      required: true
      description: "Target Windows host IP address or hostname"
    - name: service_name
      type: string
      required: true
      description: "Name of the service to start"
      
  policy:
    approval_required: true
    production_safe: false
    timeout_seconds: 120