name: systeminfo
version: "1.0"
description: "Displays detailed configuration information about computer and operating system. Legacy CMD tool, prefer Get-ComputerInfo."
platform: windows
category: system
tags:
  - system
  - info
  - configuration
  - legacy
metadata:
  execution_method: cmd
  requires_admin: false
  idempotent: true