name: Where-Object
version: "1.0"
description: "Filters objects from a collection based on property values. Essential PowerShell pipeline cmdlet."
platform: windows
category: system
tags:
  - pipeline
  - filter
  - query
  - objects
metadata:
  execution_method: powershell
  requires_admin: false
  idempotent: true