name: whoami
version: "1.0"
description: "Displays user, group, and privileges information for the current user and session."
platform: windows
category: security
tags:
  - user
  - identity
  - security
  - privileges
metadata:
  execution_method: cmd
  requires_admin: false
  idempotent: true