name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pydantic pytest mypy
      - name: Type check
        run: mypy --ignore-missing-imports shared
      - name: Tests (Phase 0 only)
        run: |
          pytest -q tests/test_shared_ids.py tests/test_shared_logging.py
