name: CI

on:
  push:
    branches: [ main, develop, 'refactor/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydantic pytest mypy
    
    - name: Run mypy on shared
      run: |
        mypy shared --ignore-missing-imports
    
    - name: Run pytest
      run: |
        pytest -q tests/test_shared_ids.py tests/test_shared_logging.py